### ISSUE TITLE
Garbage characters in shell logfiles

### ISSUE THREAD

**Issue by Hakun1n** [asbru-cm/asbru-cm#132] opened 2019-02-24 12:32 UTC
**Describe the bug**
I have session-logs enabled in global preference. "Remove control characters" is selected and "Record key pressess (record every keystroke)" is UNselected. Term emulator is set to "xterm". Character encoding is set to UTF-8

SSH log files contains weird garbage/unprintable characters and overall the log is messed. This makes reading/searching in the logs complicated.

=> Example of SSH connection via Asbru:
![image](https://user-images.githubusercontent.com/12685294/53299509-96753380-383b-11e9-98ef-60eec2378627.png)

=> Logfile from Asbru looks like this (in XED) - Note the un-printable characters as well the was that the shell-prompt has duplicate label.
![image](https://user-images.githubusercontent.com/12685294/53299510-9a08ba80-383b-11e9-8879-b3ff221f8d5b.png)

=> And this is the same log opened in "vi"
![image](https://user-images.githubusercontent.com/12685294/53299514-a260f580-383b-11e9-82be-d04f238e9e79.png)

Changing the character encoding does not help.

**Expected behavior**
Whatever is in terminal should be in the exact same form in LOGs. Connecting to the same system via PuTTy with active logging works just fine, no garbage chars recorded.

=> Log from PuTTy connection (Printable output logging selected)
![image](https://user-images.githubusercontent.com/12685294/53299520-aa209a00-383b-11e9-92b5-d810301796c9.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 29

**Comment by gfrenoy** [comment] 2019-03-10 20:59
I'm trying to reproduce this but you lost me, sorry :(

Can you let me know where you find this "Remove control characters" option ?  And what do you mean with "session-logs enabled in global preference" ?

Thanks.

**Comment by Hakun1n** [comment] 2019-03-14 11:50
Hi,

"where you find this "Remove control characters" option ?"
// See red box bellow
"And what do you mean with "session-logs enabled in global preference" ?"
// See blue box bellow

![image](https://user-images.githubusercontent.com/12685294/54354686-95277180-4657-11e9-8a56-123e651c0175.png)

**Comment by gfrenoy** [comment] 2019-03-14 22:17
Thanks for the additional information, I now understand this better !

As far as I can see, the ```_removeEscapeSeqs``` at line [251 of pac_conn](https://github.com/asbru-cm/asbru-cm/blob/cfa86036548d4a197f5abcadd35c84e8a93b5821/lib/pac_conn#L251) does not escape much or at least not as you would expect it...

I have no idea on how to improve this though ; anyone can help improving the regexps to "clean up" the output file better ?

**Comment by merikz** [comment] 2019-05-19 00:54
I saw the same years back and has been annoyed since then. Now I decided it was time to fix    _removeEscapeSeqs with code from http://unix.stackexchange.com/questions/14684/removing-control-chars-including-console-codes-colours-from-script-output.

However, when testing it I can't get it to run, pac_conn dies on SIGSEGV in the END block before the _removeEscapeSeqs is even called.

I'm in Ubuntu 18.04.2 LTS, and strace says "core dumped" at the crash, but I cannot find any dump in /var/crash. For the moment I'm stuck. Does anyone have any pointers on getting the core dump output?

I want to look at the core dump as I don't know how to attach a debugger to pac_conn. Does anyone have any hints for that?

**Comment by gfrenoy** [comment] 2019-05-19 08:10
That'd be great !  And thanks for link that indeed gives additional options :)

First, note that _removeEscapeSeqs are found two times in the code so I tried to factorize this (see [here](https://github.com/asbru-cm/asbru-cm/commit/8d13cbab824068c9b90a111742dd63eedc77aaab#diff-b066df855295868fcdd728ab78960236)).  It works fine for me but causes apparently some side issues (see #145).

Next, to debug (see FAQ), you can use [Eclipse](https://www.eclipse.org/) with [EPIC](http://www.epic-ide.org/).  I did not write down all the steps, as far as I remember it was fairly straightforward with the EPIC documentation but feel free to ask if you need help on setting that up.

**Comment by merikz** [comment] 2019-05-19 22:58
Are you saying there is a relation between _removeEscapeSeqs and $HOSTCHANGE_PROMPT? 
I haven't noticed, but maybe I'm missing something.

The problem I have with that the _removeEscapeSeqs is only run sometimes, is due to a race condition between asbru-cm and pac_conn. When the remote ssh connection is ended, pac_conn send a "DISCONNECTED" message to asbru-cm which reacts by killing pac_conn before (or during?) the _removeEscapeSeqs has happened.
The SIGSEGV seems to be caused by signal handlers being removed (?) before entering the END block where the _removeEscapeSeqs happens. I think some re-plumbing of the signal handling is needed to fix this, but there are 14 places where exit is called that invokes the END block. Touching that might have side-effects. 
But I'll see what I can do! 
 
As for debug, the issue was to get the debugger to connect to pac_conn, which is a subprocess to asbru-cm. It turns out that you, obviously, need two debugger instances. I use  a remoteDebugger in IntelliJ for the second one, which i connect with a modified `@fork_cmd` in PACTerminal. I can debug both asbru-cm and pac_conn now. (Maybe I should add that to the FAQ.)

**Comment by merikz** [comment] 2019-06-02 19:04
This is more complicated than expected. It's easy to perform a better "cleaing" of escape sequences, by just removing them completely. The log looks "nice", but wrong. The problem is that what is in the escapes are, among other things, line editing codes. For example, if I press <ctrl>-<leftarrow> (to go word-left) there is a string of backspace characters the length of the word to the left to move the insertion point. Just removing the backspace characters from the log would not result in the command given on the remote machine.
To handle all of this would mean to re-invent the vte itself just to do proper logging.
PuTTY seems to do the logging in the terminal emulation code, which in our case would be vte. But vte does not have any logging interface.

**Comment by merikz** [comment] 2019-06-06 18:40
Comment to OP; even if it does not solve the problem reported, for daily use you can turn off "Remove CONTROL characters" and read the log with `less -R`. It's not perfect, but usable.

**Comment by gfrenoy** [comment] 2019-06-16 14:57
> Are you saying there is a relation between _removeEscapeSeqs and $HOSTCHANGE_PROMPT?

Mmm, no...

> I can debug both asbru-cm and pac_conn now. (Maybe I should add that to the FAQ.)

Indeed, that'd be great :)

> This is more complicated than expected (...) To handle all of this would mean to re-invent the vte itself just to do proper logging.

Ouch yes, that's probably not the way to go :(

> you can turn off "Remove CONTROL characters" and read the log with less -R

Looks like a valid workaround to me...

Should we close this as "won't fix" ?

Thanks a lot for your contribution !

**Comment by hanspr** [comment] 2019-11-01 09:35
@KlaasT 

Think this one could be closed to

**Comment by KlaasT** [comment] 2019-11-01 09:36
Closed #132

**Closed by KlaasT** 2019-11-01 09:36 UTC
Labels: enhancement, help wanted
