### ISSUE TITLE
Remote Macro always executed without waiting for input.

### ISSUE THREAD

**Issue by Grafula** [asbru-cm/asbru-cm#622] opened 2020-05-14 13:34 UTC
Remote Macro always executed without waiting for input.

I created a remote macro containing:

ls -la as Command and 
list all as Description.

I left the "send <INTRO> at the end" box empty / unchecked.

When I run this macro it list the current colder immediately without waiting for further input or <ENTER>

**Expected behavior**
When running the macro it should wait for user input of <ENTER> key

![Screenshot from 2020-05-14 21-32-49](https://user-images.githubusercontent.com/25918060/81940820-96bd4280-962a-11ea-8517-4ed0e99b1e9a.png)

**Comment by hanspr** [comment] 2020-05-14 13:47
This is a duplicate of #605 

And you will see the fix when 6.2 is released. Should be soon.

**Comment by hanspr** [comment] 2020-05-15 16:29
6.2 has been released, install check that it works.

If it works please close the ticket to clear the board.

**Comment by gfrenoy** [comment] 2020-05-15 17:42
Just tested on my side and it works as expected with the latest 6.2.0 ; let me close it for now.  Feel free to re-open if this still should be an issue for you.

**Closed by gfrenoy** 2020-05-15 17:42 UTC
Labels: duplicate
