### ISSUE TITLE
'show GLOBAL commands' covers bottom of RDP session screen

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#687] opened 2020-09-16 12:23 UTC
Hi, as in topic. Turning on this option result with part of RDP window to be covered by a button bar.

Steps:
define global remote command
turn on 'show global commands'
log in to RDP session (embedded rdesktop in my case)

As of this topic I would like to suggest to split global commands into tabs-per-connection-type. for eg one for ssh.. one for rdp.. etc. (but thats for future plans maybe)

latest asbru loki branch
debian 10 + xfce

**Comment by gfrenoy** [comment] 2020-10-10 15:45
Confirmed:
![image](https://user-images.githubusercontent.com/981546/95659275-3b7f7580-0b20-11eb-87f1-b2bc0a4ae822.png)

Looks like we don't calculate the RDP session height correctly when `_MACROSBOX` is shown.

**Comment by gfrenoy** [comment] 2020-10-10 15:54
Just pushed a fix that worked for me.  Let us know if it helps you as well.

**Comment by vibo69** [comment] 2020-10-12 07:18
seems to be okay now ;) thanks!

**Closed** 2020-10-12 07:19 UTC
Labels: bug
