### ISSUE TITLE
Loki - EL7 - More messages in terminal 

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#588] opened 2020-04-27 10:09 UTC
Hi Team ..
Getting these messages in the terminal from where Asbru was launched:

[~]$ *** unhandled exception in callback:
***   Can't call method "hide" on an undefined value at /usr/share/asbru-cm/lib/PACTerminal.pm line 1600.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
*** unhandled exception in callback:
***   Can't call method "hide" on an undefined value at /usr/share/asbru-cm/lib/PACTerminal.pm line 1600.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
$VAR1 = undef;
$VAR1 = undef;
$VAR1 = undef;
*** unhandled exception in callback:
***   Can't call method "hide" on an undefined value at /usr/share/asbru-cm/lib/PACTerminal.pm line 1600.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.

The message from line 572 of Gtk3.pm is not new.
The $VAR1 message is new.

Thanks

**Comment by hanspr** [comment] 2020-04-27 17:31
Hi @popxunga 

I just send a patch. Thanks for your tests and reports.

Is very important to explain the context of how things happen, the error messages always help, but the context adds valuable information that is very important to fix things for good, and not by patches.

The launching of asbru-cm can not create that error, unless you have some terminals configured to launch by default.

So, Is important to specify that, and what type of terminals are launched during start up: shells?, vnc?, rdp?, ssh?, how many?, are they in some sort of cluster?.

Many of the above questions look to me to be happening in your setup, and is very important to mention it , so a precise handling of the errors can be determined.

**Comment by popxunga** [comment] 2020-04-28 08:33
Hi @hanspr ...
I'm currently too busy and I just noticed the messages in the terminal at the time I opened this issue.
At startup I'm not launching any terminals. I just launch Asbru iconified to the system tray and at that point I know there was no messages in the terminal beside the normal startup messages. So the messages were generated by my activities not sure which ones as already said.

**Comment by gfrenoy** [comment] 2020-04-28 09:19
>  Can't call method "hide" on an undefined value at /usr/share/asbru-cm/lib/PACTerminal.pm line 1600.

This one should be fixed, thanks Hans !

Let us know if you still see it.

> $VAR1 = undef;

I saw this as well.  It happens when you edit a cluster.  I tried to find out the root cause but this is outside the Ásbrú code, it's a "dump" in Gtk3::SimpleList --> https://metacpan.org/source/TVIGNAUD/Gtk3-SimpleList-0.18/lib/Gtk3/SimpleList.pm#L174

I'll create an issue in the upstream project.

**Comment by popxunga** [comment] 2020-04-28 10:17
Yap @gfrenoy ... now that you said about the Cluster edition, I just remember that I accidentally pressed the Clusters button yesterday. Just pressed it now and got the $VAR1 = unded; message.
So this one is now clarified.

**Comment by popxunga** [comment] 2020-04-28 10:27
Just tested with the latest loki build and I'm still seeing the $VAR1 = undef; message ...

**Comment by gfrenoy** [comment] 2020-04-28 10:54
> I'm still seeing the $VAR1 = undef; message ...

Yes this is expected ; this message is shown by [Gtk3::SimpleList](https://metacpan.org/release/TVIGNAUD/Gtk3-SimpleList-0.18) that is outside of the Ásbrú code base.  We cannot directly fix it.

The issue has been reported (see [here](https://rt.cpan.org/Public/Bug/Display.html?id=132441)) ; we'll need to wait for an answer (and possible follow up).

**Comment by gfrenoy** [comment] 2020-05-04 20:39
fyi issue has been fixed upstream (see [here](https://rt.cpan.org/Public/Bug/Display.html?id=132441#txn-1896384)).

We'll need to wait a bit before we get the latest version of Gtk3::SimpleList in our favorite distribution but let me close this for today as there's nothing more we can do.

**Closed by gfrenoy** 2020-05-04 20:39 UTC
Labels: bug
