### ISSUE TITLE
Compact layout is fullscreen

### ISSUE THREAD

**Issue by luca-martino** [asbru-cm/asbru-cm#778] opened 2021-02-17 08:31 UTC
Issue on asbru-cm latest release. Before, on asbru-cm-6.2.2-1.fc31.noarch worked like a charm

**Screenshots**
asbru-cm-6.3.0-1.fc31.noarch
![immagine](https://user-images.githubusercontent.com/17565704/108174983-76ae3880-7100-11eb-918c-c3faf611b842.png)

asbru-cm-6.4.0~1613482144-1.fc32.noarch
![immagine](https://user-images.githubusercontent.com/17565704/108175200-c1c84b80-7100-11eb-8cad-60225e709668.png)

**Expected behavior**
the well known and appreciate compact menu

**Environment:**
 - OS: Fedora release 32 (Thirty Two) x86_64
 - DE: GNOME 3.36.7
 - Theme: WhiteSur-dark [GTK2/3]
 - Ásbrú Version [6.3.0-1.fc31 and now 6.4.0 loki]
 
 **Additional context:**
Had to revert to 6.2.2 that is working without a problem.
![immagine](https://user-images.githubusercontent.com/17565704/108210187-82632480-712b-11eb-8e0a-4691a9008c65.png)

**Comment by gfrenoy** [comment] 2021-02-17 22:49
I made some tests but I cannot reproduce the issue so far.

Do you see the same behaviour if you start from a "clean" configuration:

```
asbru-cm --config-dir=/tmp/asbru-test
```

?

**Comment by luca-martino** [comment] 2021-02-18 06:56
It's ok on a clean configuration:
![immagine](https://user-images.githubusercontent.com/17565704/108317616-d79c4600-71be-11eb-9b56-c7292aea6721.png)

**Comment by gfrenoy** [comment] 2021-02-18 17:41
> so now?

We need to understand what is "wrong" in your configuration.

I don't have any idea at this stage so here are a few wild guess to investigate:

- Delete the file `asbru.yml.gui`  (it will be recreated)
- Send me an anonymized version of your configuration (see "Export Config..." in Preferences)
- Copy `asbru.yml` from your orginal configuration directory to the new one and delete `asbru.dumper` before you restart Ásbrú from the temporary configuration

**Comment by luca-martino** [comment] 2021-02-19 08:52
> > so now?
> 
> We need to understand what is "wrong" in your configuration.
> 
> I don't have any idea at this stage so here are a few wild guess to investigate:
> 
>     * Delete the file `asbru.yml.gui`  (it will be recreated)
> 
>     * Send me an anonymized version of your configuration (see "Export Config..." in Preferences)
> 
>     * Copy `asbru.yml` from your orginal configuration directory to the new one and delete `asbru.dumper` before you restart Ásbrú from the temporary configuration

First run of a clean asbru-cm 6.3.0 (--config-dir=/tmp/asbru-test) is OK.
- Deleted `asbru.yml.gui` and `asbru.dumper`
- Copy of original `asbru.yml` to /tmp/asbru-test
- Second run asbru-cm --config-dir=/tmp/asbru-test --> KO "compact layout"
![immagine](https://user-images.githubusercontent.com/17565704/108481041-f6bad680-7297-11eb-9b12-bcc915c892f7.png)

**Comment by gfrenoy** [comment] 2021-02-20 09:21
Thanks for the additional information !  I have been able to reproduce the issue.

It is related to "Iconified in 'systray'" option:
![image](https://user-images.githubusercontent.com/981546/108590723-4b785300-7365-11eb-9ac7-46d01f21dd60.png)

If you uncheck it, it should work better (until I can fix the issue...).

**Comment by gfrenoy** [comment] 2021-02-20 10:08
Ok I understand the root issue now:  the "Start maximized" option is still checked but you can only change it in "Traditional" mode:

![image](https://user-images.githubusercontent.com/981546/108591980-c5133f80-736b-11eb-9e47-37d8f47d5917.png)

I'll make a change to fix that automatically but in the meantime:
1) Revert to "Tranditional mode"
2) Check "At start > With last size"
3) Save configuration
4) Set "Compact mode"
5) Save configuration

And the problem should be fixed for you...

**Comment by gfrenoy** [comment] 2021-02-21 10:54
The last commit shall fix the initial "maximize" issue.  It will be available in a few minutes in the snapshot release.  And included in the "to be" version 6.3.1 soon.

**Comment by luca-martino** [comment] 2021-02-22 13:06
Issue fixed


> Ok I understand the root issue now: the "Start maximized" option is still checked but you can only change it in "Traditional" mode:
> And the problem should be fixed for you...

![immagine](https://user-images.githubusercontent.com/17565704/108712426-098f0e80-7517-11eb-8a56-2563308fa3eb.png)

**Closed** 2021-02-22 21:53 UTC
Labels: bug
