### ISSUE TITLE
Connection information is lost after closing the program

### ISSUE THREAD

**Issue by marufmax** [asbru-cm/asbru-cm#964] opened 2022-07-27 14:27 UTC
**Describe the bug**
When creating a new connection the button `save and close` did not respond

**To Reproduce**
1. Go to New connection
2. Enter connection information
3. Click on 'Save and Close'
4. Nothing happens

After re-opening `asbru-cm` previously stored information is lost

**Expected behavior**
Should be save the connection information

**Screenshots**
[Screen Record](https://youtu.be/jq33ztn1U7M)

**Environment (please complete the following information):**
 - OS: Manjaro KDE 
`cat /etc/lsb-release`
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.3.5
DISTRIB_CODENAME=Ruah
DISTRIB_DESCRIPTION="Manjaro Linux
 ```
KDE plasma 5.24.6
 - Ásbrú Version `git clone from master branch`

**Comment by ergotone** [comment] 2022-08-08 19:00
confirm this happesn on Ubunto 20 as well (sometimes **_can_** store, but it disappears on next opening of program)

**Comment by marcogiorgio** [comment] 2022-08-28 14:12
This happens even in Linux Mint 21 (Ubuntu 22.04 repo)

**Comment by mindsolve** [comment] 2022-09-04 23:54
Hi, this is probably related to #856 (and numerous duplicate issues) - this is already fixed on the "loki" branch, see the latest comment on that issue.

I can confirm that the issue is resolved with the version from the loki repo, while the latest release from the "snapshot" repo on Ubuntu still has that issue.

**Comment by marufmax** [comment] 2022-09-05 05:22
This should be merged as hotfix

**Comment by gfrenoy** [comment] 2022-11-03 21:34
Thanks for reporting the issue, this is indeed a consequence of #816 that is fixed on the `loki` branch.
Let's focus on energy on releasing that version !

**Closed by gfrenoy** 2022-11-03 21:34 UTC
Labels: duplicate
