### ISSUE TITLE
Asbru lost all connection settings after close 

### ISSUE THREAD

**Issue by darksoft2021** [asbru-cm/asbru-cm#979] opened 2022-10-01 22:41 UTC
**Describe the bug**
1. I add connection, paste user, IP, password.
2. I connect and work
3. I close program
4. After open - I have not connect settings

**Environment (please complete the following information):**
 - OS: Ubuntu Ubuntu 22.04.1 LTS
 - Ásbrú Version 6.3.3

**Comment by kobzardmytro** [comment] 2022-10-03 21:43
Hello, same problem, in pop os 22.04

**Comment by shotty53** [comment] 2022-10-04 18:50
I am having the same issue. I am running Arch linux and have installed multiple times/ways and all the same problem.
Installed via packman, pikaur, and makepkg: asbru-cm-git 6.3.3.r2.g1c06e77-1 and asbru-cm-git 6.3.3.r1.gac61921-1
Each have the same issue where I can configure as many devices as I need. Upon closing out the application and re-opening, the connection list is empty.

**Comment by madhu-liferay** [comment] 2022-10-13 03:04
Same for Fedora 36, seems like a regression issue?

**Comment by dennisTGC** [comment] 2022-10-18 14:40
I have this issue (reproducable) if I have multiple asbru-cm applications open. I start asbru with the following command:
```
env GDK_BACKEND=x11 asbru-cm --config-dir='/home/someurl/Asbru/Asbru-customers1'
```
and a different session goes to customers2. Only the setting of the first started asbru get saved. I also have the setting `Automatically save every configuration change` turned on. v6.3.3 on ubuntu 22.04.1

Let me know if I can help troubleshooting!

**Comment by dennisTGC** [comment] 2022-10-27 17:26
Ok, this is what I found:
```
INFO: Ásbrú is already running.
INFO: Starting '/usr/bin/asbru-cm' in READ ONLY mode!
```

So that explains not saving the changes.. That leads to the question if this is by design or not.  I think this is a safety measure to prevent asbru-cm to write from 2 instances, but as  I start with `--config-dir` I would want to save my changes in every config dir, right? So I think asbru-cm shouldn't start in read-only mode if the parameter `--config-dir` is being used? I'm guessing here, so enlight me if I'm wrong.

**Comment by madhu-liferay** [comment] 2022-10-28 04:07
Tried using the config-dir, didnt work
env GDK_BACKEND=x11 asbru-cm --config-dir='/madhu/docs/misc/asbru-configs'

Also noticed the below error while saving a new connection, could be related
WARNING: The key derivation method "opensslv1" is deprecated. Using -pbkdf=>'pbkdf2' would be better.
Pass -nodeprecate=>1 to inhibit this message.
 at /usr/share/asbru-cm/lib/PACUtils.pm line 2718.
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /usr/share/asbru-cm/lib/PACUtils.pm line 2718.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.

**Comment by jetbalsa** [comment] 2022-11-03 15:47
This is because of issue #816 You will need to patch your PACUtils with the code of ```my $CIPHER = Crypt::CBC->new(-key => 'PAC Manager (David Torrejon Vaquerizas, david.tv@gmail.com)', -cipher => 'Blowfish', -salt => '1', -pbkdf => 'opensslv1', -nodeprecate => 1) or die "ERROR: $!";``` near line 145 -- I am submitting a PR for this to fix this.

**Comment by gfrenoy** [comment] 2022-11-03 21:43
Thanks all for your feedbacks and comments.

6.3.3 will not work on recent distros, we need to release 6.4.0 that already has all the fixes; let's focus our energy on releasing that new version !

**Closed** 2022-11-03 21:44 UTC
Labels: duplicate
