### ISSUE TITLE
Error prevents RDP session from starting

### ISSUE THREAD

**Issue by piovisqui** [asbru-cm/asbru-cm#57] opened 2018-01-29 14:01 UTC
Hi folks.

I installed Asbru using the instructions from the website. While PAC still works for me, I tried Asbru and can't connect, it throws the following error when opening a RDP connection.
```

Gtk-WARNING **: Não foi possível localizar a ferramenta de temas no module_path: "murrine", at /usr/share/asbru-cm/lib/edit/PACMethod.pm line 47.
Gtk-WARNING **: Não foi possível localizar a ferramenta de temas no module_path: "murrine", at /usr/share/asbru-cm/lib/edit/PACMethod.pm line 47.
INFO: Using 'Unity' tray icon
Gdk-WARNING **: Couldn't match property type UTF8_STRING to STRING
GLib-CRITICAL **: Source ID 2077 was not found when attempting to remove it at /usr/share/asbru-cm/lib/PACTerminal.pm line 1175.
GLib-CRITICAL **: Source ID 2077 was not found when attempting to remove it at /usr/share/asbru-cm/lib/PACTerminal.pm line 1008.
Finishing (asbru-cm) with pid 17055
GLib-CRITICAL **: Source ID 2077 was not found when attempting to remove it at /usr/share/asbru-cm/lib/PACTerminal.pm line 444.
Finished asbru-cm (PID:17055)...
```

The system is Fedora 26 with KDE and the connection is xfreerdp "embed in tab".

This problmem was reported to [PAC bugtracker](https://sourceforge.net/p/pacmanager/discussion/1076055/thread/7ea5bd5c/?limit=25), which makes it really weird, since PAC works for me and Asbru don't.

**Comment by gfrenoy** [comment] 2018-02-01 21:52
Even if I don't think this is the root reason, about the "murrine" message, I guess this should help ([ref](https://superuser.com/questions/337639/unable-to-locate-theme-engine-in-module-path-murrine)):

    sudo yum install gtk2-engines gtk-murrine-engine

About the bug reported on PAC bugtracker, even if the error message looks similar, I don't think it is related.

Now, to stay focus on the RDP connection, I made some tests here but all works fine on my environment.  I can more or less reproduce the same problem if I intentionally make a mistake in the RDP connection parameters.  Then Ásbrú is not really nicely properly catching the issue.  A blank tab is shown and a "Source ID not found" message is shown in the console.

Are you 100% sure that the RDP connection parameters are correct and the same as with PAC ?

**Comment by gfrenoy** [comment] 2018-02-01 22:07
Fyi, I also made a test on a fresh Fedora 26 KDE live image and it worked fine:

![image](https://user-images.githubusercontent.com/981546/35706030-90f9c786-07a4-11e8-987b-2ff579581411.png)

**Comment by piovisqui** [comment] 2018-02-02 18:35
Installing the murrine engine did not help. I noticed this error only occurs when opening an embed RDP session, if I use a separate windows it works.

**Comment by gfrenoy** [comment] 2018-02-02 23:21
> Installing the murrine engine did not help.

Yes, that was expected...But thanks for checking!  We can for sure forget about that message now.

> I noticed this error only occurs when opening an embed RDP session, if I use a separate windows it works.

Ok this is interesting.

Can you send the log of what you see after you tried the connection ?  I mean, without closing the application ?

If you can make a screenshot (I'm using [Shutter](http://shutter-project.org/)), this might give some more ideas as well...

**Comment by marcinbojko** [comment] 2018-02-19 16:57
Is it a xfreerdp or rdesktop session? If the former - mark 'ignore verification of logon certificate'

**Comment by marcinbojko** [comment] 2018-02-19 16:58
@gfrenoy - I cannot express how happy I am for you guys to pick the project. It's one of my most used tools under Linux - so please, where is 'donation' button? :) I'd be a first! ;)

**Comment by piovisqui** [comment] 2018-02-19 17:40
@gfrenoy  The log I posted before is everything that shows up.

**Comment by gfrenoy** [comment] 2018-02-19 21:02
@piovisqui what I mean is : from the log, I see that Ásbrú has been terminated.  This might also have generated some logs ; I would like to understand the difference between the log when the RDP session failed and the log when you stopped Ásbrú.

Also 2 separate logs when it succeeds (separate window) and when it fails (embed) will maybe ring some bells...

(Any kind of information since I'm really lost and don't see why it works for me and not for you)

**Comment by gfrenoy** [comment] 2019-04-19 13:40
Closing due to inactivity.  Feel free to re-open if there's anything new to share.

**Closed by gfrenoy** 2019-04-19 13:40 UTC
Labels: more information needed
