### ISSUE TITLE
print() on closed filehandle $CMD at /opt/asbru/lib/asbru_conn line 1320.

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#700] opened 2020-10-08 09:58 UTC
this happens at random times when i try to open saved ssh connection. i believe this is after i edit cloned connection and try to open the new one when old one is also opened

debian 10+xfce4. latest loki

**Comment by hanspr** [comment] 2020-10-09 15:37
@gfrenoy 

That is new code I do not recognise, but by the look of it, the

```
open(my $CMD, ">:utf8", $cmd_file);
```

Should be tested to succeed and not assume that will work.

```
if (open(my $CMD, ">:utf8", $cmd_file)) {
    chmod(0400, $CMD);                  
    print { $CMD } $connection_cmd;     
    close($CMD);                        
    $do_connection_cmd = "sh $cmd_file";
}
```

And some debugin should be done to understand why it fails to open the file.

**Comment by gfrenoy** [comment] 2020-10-09 16:42
> Should be tested to succeed and not assume that will work

Absolutely !

> why it fails to open the file

Or maybe it's already closed ?  If we open twice the same connection at the same time ... As the name is based on the same `$UUID`, does not look very nice...

 > chmod(0400, $CMD);

I cannot make any sense of this, I'd just assume it was an unfortunate typo :(

**Comment by gfrenoy** [comment] 2020-10-16 23:32
Made a change that should ensure the file is not closed when writing in it (since it is supposed to be unique now).

Let me know if you see that message again...

**Comment by popxunga** [comment] 2020-10-17 11:06
Hi ...
Just tested with latest loki build (asbru-cm-6.3.0~1602891514-1.el8).
I was able to reproduce the issue using the previous loki build by repeatedly open the same ssh remote connection.
The first one open's cleanly while the subsequent sessions usually display the error message.
I'm no longer able to see the error message using this procedure using the latest loki build and so I think that this problems is solved.
Thanks for your support.

**Comment by gfrenoy** [comment] 2020-10-17 14:06
@popxunga thanks for the test and the feedback :)  Let's close it for now and re-open it if one can reproduce this in a different way.

**Closed by gfrenoy** 2020-10-17 14:06 UTC
Labels: awaiting feedback, bug
