### ISSUE TITLE
Auto hide main button

### ISSUE THREAD

**Issue by kabhotz** [asbru-cm/asbru-cm#386] opened 2020-01-28 16:39 UTC
After few tests in Centos 7 I have found this bug:

Open Asbru go to:
Preferences / Main Options / Look and Feel

Put the flag on:
"Auto hide main button bar on Terminal Open"

Test:
Open a local shell or try a remote connection

The main button bar is not hide after connections (the main button bar is the bar where are stored all the connection rules).

Let me know if you need other information!
Thanks for your work!
K.

**Comment by hanspr** [comment] 2020-01-29 12:57
Hi @kabhotz 

On the same Configuration window, there is an export button, select the second option "Anonimized data for DEBUG".

![imagen](https://user-images.githubusercontent.com/1572396/73358332-fe11db00-4263-11ea-8e46-355d8f45e9c5.png)

This should save your configuration file removing all sensitive information, please check the file that does not have any sensitive information in it. Then upload here so we can take a look. Sometimes this errors happen when some options are combined.

If by any change the process left sensitive information, please let us know what it was so we can improve that export functionality.

**Comment by gfrenoy** [comment] 2020-01-29 14:10
Cannot reproduce the issue either.

> the main button bar is the bar where are stored all the connection rules

Mmm, the "button bar" is the bar under the terminal that shows some control buttons:
![image](https://user-images.githubusercontent.com/981546/73363536-38ea3200-42a9-11ea-8184-274d535ed3c1.png)

Are you looking at the right bar ?

**Comment by kabhotz** [comment] 2020-01-31 09:51
Hello @hanspr, here in attached the debug file.
[debug.yml.zip](https://github.com/asbru-cm/asbru-cm/files/4138564/debug.yml.zip)

@gfrenoy the main button bar is the lateral left bar with all the connections, probably there is an error in translation.
![Screenshot from 2020-01-31 10-46-54](https://user-images.githubusercontent.com/8977332/73529473-078f7480-4417-11ea-909e-35ed37e9bfe6.png)

Please try the same configuration in PAC to see the differences on new connections.
In PAC the "main button bar" is hide to give more space to the terminal and moving the mouse on the left of the window the bar appear automatically.

Let me know if you need other information to reproduce the error.

**Comment by hanspr** [comment] 2020-01-31 16:35
Thank you for your debugin file.

As marked in the image below, option (1) Closes the "Connections List", and option (2) the "Button bar"

Activate option (1) and it will work as you expect.

![imagen](https://user-images.githubusercontent.com/1572396/73556478-22f98000-4415-11ea-9d05-da27db17d160.png)

Please close the issue if it works.

We will improve the non existing manuals one day, sorry :worried:

**Comment by kabhotz** [comment] 2020-02-04 10:04
Thanks for the explanation, I have misinterpreted the translations.

In any case I have tried again the option "Hide connections list (on terminal open)" and it hide the list panel from the terminal but doesn't show the panel in the "Info" tab.

In PAC the connection list it's always displayed in the "Info" panel, in other case isn't possible to make multiple connections.

PAC example with hide list enabled:
![Screenshot from 2020-02-04 11-02-08](https://user-images.githubusercontent.com/8977332/73734430-ed6ad480-473d-11ea-9f40-52236af94c1a.png)

ASBRU example with hide list enabled:
![Screenshot from 2020-02-04 11-00-52](https://user-images.githubusercontent.com/8977332/73734469-f8be0000-473d-11ea-9a65-437e7b133cd0.png)

Thanks in advance!

**Comment by hanspr** [comment] 2020-02-04 13:54
@kabhotz 

You can show/hide the Connection list again at any time clicking on the "Connection List Icon". Without having to go to the "Info tab".

![imagen](https://user-images.githubusercontent.com/1572396/73750306-8d1a6980-4722-11ea-962d-e84e723f1212.png)

I will check if there is any code that says that by clicking on the info tab the "Connection list" should show up again if hidden. If not, I guess the behaviour was removed by accident and see if I can bring it back.

**Comment by kabhotz** [comment] 2020-02-04 14:01
The more vantage to have the connection list in the info tab is that I don't have to use the mouse and I can open a new connection just with keyboard.

In any case thanks for your work.
Regards.

**Comment by hanspr** [comment] 2020-02-04 14:17
@kabhotz 

>The more vantage to have the connection list in the info tab is that I don't have to use the mouse and I can open a new connection just with keyboard.

I understand that, that is why I said I was going to bring it back.

Please open the issue again, I'm sending a PR to add the functionality you described, it will help us keep track of correcting the issue.

**Comment by kabhotz** [comment] 2020-02-04 14:19
Thanks! :)

**Closed** 2020-02-04 14:33 UTC
Labels: invalid
