### ISSUE TITLE
rdesktop/xfreerdp issue on asbru-cm-6.5.0 (Compact Layout)

### ISSUE THREAD

**Issue by luca-martino** [asbru-cm/asbru-cm#1103] opened 2024-08-16 09:23 UTC
**Describe the bug**
Unable to make rdp session after asbru-cm update (loki asbru-cm-6.5.0~1723751537-1.fc37.noarch), also all the tabs are "red colred" (local, rdp, ssh)

**Expected behavior**
establishing rdp session as in the previous arbru-cm version (Window Layout -> Compact)

**Screenshots**
![immagine](https://github.com/user-attachments/assets/162e7a79-6cc5-433f-aaa1-8219faf0002f)

**Environment (please complete the following information):**
 - OS: Fedora Linux 40 (Workstation Edition) x86_64 - Kernel: 6.10.4-200.fc40.x86_64
 - Ásbrú Version [6.5.0 loki]

**Additional info**
asbru-cm --verbose
INFO: Ásbrú Connection Manager 6.5.0 (asbru-cm) started with PID 18412
INFO: Language detected : it_IT.UTF-8, forcing to en_US.UTF-8
INFO: Config directory is '/home/xeon/.config/asbru'.
INFO: Locking configuration file with '/home/xeon/.config/asbru/lock'.
INFO: Path for temporary files: /tmp/asbru-cm-3wln
INFO: Desktop environment detected : gnome-shell:gnome-xorg-withtray
INFO: Crypt::CBC version is 3.04
INFO: Used config file '/home/xeon/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.76
       - has_bright = 1
       - major_version = 0
       - minor_version = 76
       - vte_feed_binary = 1
       - vte_feed_child = 1
INFO: Theme directory is '/usr/share/asbru-cm/res/themes/asbru-dark'
INFO: Using Gnome tray icon
DEBUG: Starting window position = (2928, 206} ; window size (220, 600)
INFO: Loading tree configuration from '/home/xeon/.config/asbru/asbru.yml.tree'.
Use of uninitialized value in concatenation (.) or string at /usr/share/asbru-cm/lib/PACTerminal.pm line 444.
DEBUG: Saving window position = (2928, 228) ; window size (220, 600)
*** unhandled exception in callback:
***   **Can't call method "set_image" on an undefined value at /usr/share/asbru-cm/lib/PACTerminal.pm line 2485.**
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
*** unhandled exception in callback:
***   Can't call method "set_image" on an undefined value at /usr/share/asbru-cm/lib/PACTerminal.pm line 2485.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
*** unhandled exception in callback:
***   Can't call method "set_image" on an undefined value at /usr/share/asbru-cm/lib/PACTerminal.pm line 2485.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
...
** Main Window Layout Traditional **
![immagine](https://github.com/user-attachments/assets/42524ee1-c957-4fb9-84ea-c4510f99e8e9)
Everything is working fine on "Traditional" layout

**Comment by gfrenoy** [comment] 2024-08-16 10:47
Compact mode was indeed not tested, sorry about that.
The issue is now fixed, please update to the latest loki release.

**Comment by luca-martino** [comment] 2024-08-16 11:26
> Compact mode was indeed not tested, sorry about that. The issue is now fixed, please update to the latest loki release.

 works like a charm, as alway ... well done

**Closed** 2024-08-16 11:28 UTC
