### ISSUE TITLE
Right-click on connection-tree changes selection

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#51] opened 2018-01-17 10:53 UTC
If I select multiple entries in the connection tree (e.g. using <shift>+left-click) and then rightclick on one of those entries without holding <shift>, the selection changes to only select the item I clicked on.

This is contrary to the behavior I'm used to in other software (e.g. Nautilus, Windows Explorer, etc.) where the selection doesn't change on rightclick.

Steps to reproduce:
Preparation:
Create a group with child elements 1, 2, 3, 4, 5, 6, 7, and 8.

Szenario A:
1. Leftclick on "1"
2. hold <shift>
3. Leftlick on "8" -> elements "1" to "8" are now selected
4. While still holding <shift> rightclick on "4" -> Selection changes to "1" to "4"; "5" to "8" are no longer selected

Szenario B:
1. Leftclick on "2"
2. hold <ctrl>
3. Leftclick on "4", "6", and "8" -> all even numbered entries are now selected
4.1. While still holding <ctrl> rigthclick on "8" -> the selection changes and "8" is no longer selected
4.1. release <ctrl> and click on "8" -> the selection changes and only "8" is selected

Let me know if I could clarify things a little more.

If I have the elements  and select them by leftclick->1; hold <shift>+leftlick->8

**Comment by gfrenoy** [comment] 2018-01-21 09:21
Into my eyes, it re-selects only one entry because there is nothing foreseen to manage multiple entries inside the same single menu.  Said differently, this requests probably goes further that only keeping the selected items active, isn't it ?

**Comment by hanspr** [comment] 2019-11-01 09:38
@KlaasT 

This is a duplicate of #168 

Which has been fixed

**Comment by KlaasT** [comment] 2019-11-01 09:40
Duplicate of #168.
Closed #51

**Closed by KlaasT** 2019-11-01 09:40 UTC
Labels: enhancement, more information needed
