### ISSUE TITLE
Support for Ubuntu 21.10 (Impish Indri)

### ISSUE THREAD

**Issue by dary-winata** [asbru-cm/asbru-cm#861] opened 2021-11-01 07:42 UTC
When i adding some gpg key into  apt, i got error.

1.  curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash

This is my screenshot when trying to execute that line.
![Screenshot from 2021-11-01 14-42-03](https://user-images.githubusercontent.com/71117097/139638168-4bc94993-d679-44d9-b977-0e518a35771b.png)

My Environtment is:
 - OS: Ubuntu 21.10
 - Ásbrú Version: latest

Thank you

**Comment by anatol06** [comment] 2021-11-03 14:22
Same Issue
![image](https://user-images.githubusercontent.com/9899389/140078433-59bf1a18-ec13-4a6a-82a4-e3356e36dcaa.png)

**Comment by gfrenoy** [comment] 2021-11-06 20:03
The build for Ubuntu Impish (21.10) is now available in our snapshot release (see https://docs.asbru-cm.net/General/Installation/).

And it will be available on our main repository as soon as 6.3.3 will be released.

**Comment by dary-winata** [comment] 2021-11-10 05:02
sorry for the delay, i still got the error when installing the new version of asbru-cm, eventhough im successfully installed asbru-cm/snapshots repository via apt, i still got error "Unable to locate package asbru-cm"
![Screenshot from 2021-11-10 12-02-00](https://user-images.githubusercontent.com/71117097/141052946-3d1196eb-64c1-46c1-b982-cef7b0215e0f.png)

**Comment by gfrenoy** [comment] 2021-11-13 11:09
Really strange, the build was sucessful and the package correctly pushed to cloudsmith.io:
  https://app.travis-ci.com/github/asbru-cm/asbru-cm/jobs/546981664#L1029-L1030

But it's indeed not there:
  https://cloudsmith.io/~asbru-cm/repos/snapshots/packages/?q=distribution%3Aubuntu+AND+distribution%3Aimpish

(only the "dsc" has been pushed correctly).

Let's hope it's only a one time issue and that the next build will make it...

**Comment by gfrenoy** [comment] 2021-11-13 15:04
I re-ran the build.  Strangely enough, the package fails to synchronize on cloudsmith:
![image](https://user-images.githubusercontent.com/981546/141648686-7bbd499c-d97d-4b7c-a4e6-695f7bed5642.png)

https://cloudsmith.io/~asbru-cm/repos/snapshots/packages/detail/asbru-cm_6331636813057-1_alldeb-jnP/#metadata

Don't understand why :-(  Any suggestion or idea will be appreciated.

**Comment by gfrenoy** [comment] 2021-11-16 17:00
So the root cause of the synchronization seems to be the compression format inside the .deb package:

> ﻿sync dpkg-deb: error: .......asbru-cm_6.3.3~1637010459-1_all.deb' uses unknown compression for member 'control.tar.zst'

As of impish (see [here](https://launchpad.net/ubuntu/+source/dpkg/1.20.9ubuntu2)), the default is now `zst` instead of `xy` and cloudsmith.io does not support this yet.

I did try to find how to force the compression algorithm with packpack but this is apparenlty not foreseen :(

**Comment by gfrenoy** [comment] 2021-11-28 14:05
So far I did not find any way to force `xy` in packack.  On the other hand, our partners from cloudsmith confirmed the issue and are working on a fix.  Not ETA now but I'm confident it is high enough in their priorities so let's be patient for now.

**Comment by dary-winata** [comment] 2021-11-29 08:47
thanks appreciate that, I would be waiting patiently for it thanks. Should i close this Issue? sorry Im new to GitHub.

**Comment by gfrenoy** [comment] 2021-11-29 18:58
> Should i close this Issue? sorry Im new to GitHub.

Leave it open until we find a solution.

**Comment by abhaysap** [comment] 2021-12-05 10:44
As per the link (https://docs.asbru-cm.net/General/Installation/) even the build for Ubuntu Impish (21.10)  available as snapshot release is not working.

**Comment by killmasta93** [comment] 2021-12-18 21:43
does this support ubuntu 21.10? I have tried installing but wont install

` curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash`
```

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=21.10  codename=impish  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

```

but i get this

```
sudo apt install asbru-cm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package asbru-cm

```

**Comment by abhaysap** [comment] 2021-12-19 04:18
See #861  there is already a bug open waiting for the support 

RegardsAbhay Sapru+919930653403 

    On Sunday, 19 December, 2021, 03:13:37 am IST, killmasta93 ***@***.***> wrote:  
 
 


does this support ubuntu 21.10? I have tried installing but wont install

 curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=21.10  codename=impish  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!


but i get this
sudo apt install asbru-cm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package asbru-cm


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by killmasta93** [comment] 2021-12-19 14:11
thanks for the reply, would it work with ubuntu 21.04? or should i just drop down to 20?

**Comment by abhaysap** [comment] 2021-12-19 14:33
yes it will work 
RegardsAbhay Sapru+919930653403 

    On Sunday, 19 December, 2021, 07:42:02 pm IST, killmasta93 ***@***.***> wrote:  
 
 


thanks for the reply, would it work with ubuntu 21.04? or should i just drop down to 20?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gfrenoy** [comment] 2021-12-27 12:57
>  would it work with ubuntu 21.04?

Yes it will work "out of the box".  But even with impish, it will work fine if you force the use of another repository ; this is actually the same Ásbrú package ; try this:

`
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | version=21.04 codename=hirsute sudo -E bash
sudo apt install asbru-cm
`

Note: you will need to add universe & multiverse ubuntu repositories

**Comment by abhaysap** [comment] 2022-01-03 13:17
its not working for version 21.10
sudo curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | version=21.10 codename=impish sudo -E bash sudo apt install asbru-cm/usr/bin/sudo: /usr/bin/sudo: cannot execute binary file


RegardsAbhay Sapru+919930653403 

    On Monday, 27 December, 2021, 06:40:54 pm IST, Gaëtan Frenoy ***@***.***> wrote:  
 
 



would it work with ubuntu 21.04?


Yes it will work "out of the box". But even with impish, it will work fine if you force the use of another repository ; this is actually the same Ásbrú package ; try this:

curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | version=21.04 codename=hirsute sudo -E bash sudo apt install asbru-cm

Note: you will need to add universe & multiverse ubuntu repositories

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by abhaysap** [comment] 2022-01-03 13:34
sudo curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash[sudo] password for sunny: Sorry, try again.[sudo] password for sunny: Executing the  setup script for the 'asbru-cm/release' repository ...
   OK: Checking for required executable 'curl' ...   OK: Checking for required executable 'apt-get' ...   OK: Detecting your OS distribution and release using system methods ... ^^^^: ... Detected/provided for your OS/distribution, version and architecture: >>>>: >>>>: ... distro=ubuntu  version=21.10  codename=impish  arch=x86_64   >>>>: NOPE: Checking for apt dependency 'apt-transport-https' ...   OK: Updating apt repository metadata cache ...   OK: Attempting to install 'apt-transport-https' ...   OK: Checking for apt dependency 'ca-certificates' ...   OK: Checking for apt dependency 'gnupg' ...   OK: Importing 'asbru-cm/release' repository GPG key into apt ...   OK: Checking if upstream install config is OK ...   OK: Installing 'asbru-cm/release' repository via apt ...   OK: Updating apt repository metadata cache ...   OK: The repository has been installed successfully - You're ready to rock!
***@***.***:~$ sudo apt install asbru-cmReading package lists... DoneBuilding dependency tree... DoneReading state information... DoneE: Unable to locate package ***@***.***:~$ 



RegardsAbhay Sapru+919930653403 

    On Monday, 3 January, 2022, 06:47:15 pm IST, abhay sapru ***@***.***> wrote:  
 
 its not working for version 21.10
sudo curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | version=21.10 codename=impish sudo -E bash sudo apt install asbru-cm/usr/bin/sudo: /usr/bin/sudo: cannot execute binary file


RegardsAbhay Sapru+919930653403 

    On Monday, 27 December, 2021, 06:40:54 pm IST, Gaëtan Frenoy ***@***.***> wrote:  
 
 



would it work with ubuntu 21.04?


Yes it will work "out of the box". But even with impish, it will work fine if you force the use of another repository ; this is actually the same Ásbrú package ; try this:

curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | version=21.04 codename=hirsute sudo -E bash sudo apt install asbru-cm

Note: you will need to add universe & multiverse ubuntu repositories

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gfrenoy** [comment] 2022-01-03 20:26
@abhaysap please read [my last comment](https://github.com/asbru-cm/asbru-cm/issues/861#issuecomment-1001556672) carefully.  In particular, it will only work for our `snapshots` repository.  You are trying on the `release` repository.

**Comment by gfrenoy** [comment] 2022-05-15 09:33
I believe I finally found a [workaround](https://github.com/asbru-cm/asbru-cm/commit/52ed54af8c9bd38aceb1a510e2e59009f2c62543) to upload our .deb package to Cloudsmith, see:
  https://cloudsmith.io/~asbru-cm/repos/loki/packages/detail/deb/asbru-cm/6.4.0~1652606071-1/

It's only available on the loki branch so far ; if confirmed working, I will apply the trick to more distribs.

Can someone give it a try and provide feedback ?

**Comment by gfrenoy** [comment] 2022-05-16 20:44
As far as I can see/test, my "repack" trick looks to work.

Ásbrú is now available on the `loki` and `snapshots` repositories for Impish.

**Closed by gfrenoy** 2022-05-16 20:44 UTC
Labels: enhancement, awaiting feedback
