### ISSUE TITLE
Package for Ubuntu 20.04

### ISSUE THREAD

**Issue by StormTrooper** [asbru-cm/asbru-cm#585] opened 2020-04-24 15:31 UTC
Any ETA on when there will be a package for Ubuntu 20.04 Focal Fossa.

NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"

I can install the version from 19.10 manually and it works, but the automated script fails as there is no build yet for 20.04

**Comment by KlaasT** [comment] 2020-04-24 15:36
Shouldn't take too long. We don't have a docker image for the build process ready yet.

**Comment by StormTrooper** [comment] 2020-04-24 15:40
Thanks. Didn't see a issue was already opened for this. 

https://github.com/asbru-cm/asbru-cm/issues/571

**Comment by jdrch** [comment] 2020-04-24 16:18
As a workaround until official 20.04 support hits the stable repo, if you run the [testing build installation script](https://github.com/asbru-cm/asbru-cm#testing-new-features) on 20.04 it installs and runs just fine.

**Comment by KlaasT** [comment] 2020-04-26 06:30
Closed as duplicate of #571

**Closed by KlaasT** 2020-04-26 06:30 UTC
Labels: duplicate
