### ISSUE TITLE
Remote commands: Send <INTRO> at the end always working

### ISSUE THREAD

**Issue by EduardMalik** [asbru-cm/asbru-cm#605] opened 2020-05-07 07:02 UTC
**Describe the bug**
From docs: Send **INTRO** at the end : Will send or not a \n at the end of the command string. Uncheck if you command requires you to type some extra information before sending the <Enter> key. I uncheck this options, but my command execute always, Enter key always sending.

**To Reproduce**
1. Go to 'Remote Commands'
2. Click on 'Add'
3. Add Command: echo test
4. Uncheck end **INTRO** at the end
5. Connect, right click, select in menu remote commands, echo test
6. Command run without waiting enter press

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Ásbrú Version 6.1.3
 - Remote servers: Debian 7.8, Centos 6.9, Centos 7.6

**Comment by hanspr** [comment] 2020-05-07 19:02
Could not reproduce in "Remote Commands" nor "Remote macros".

Linux Mint

![imagen](https://user-images.githubusercontent.com/1572396/81333786-b07aea80-906a-11ea-8287-47d2802ff2df.png)

![imagen](https://user-images.githubusercontent.com/1572396/81333515-5a0dac00-906a-11ea-8a72-8d0ec2cfff5c.png)

![imagen](https://user-images.githubusercontent.com/1572396/81333526-5e39c980-906a-11ea-9827-6c3ed0c7f4fb.png)

![imagen](https://user-images.githubusercontent.com/1572396/81333565-6abe2200-906a-11ea-8fc0-ba500420a394.png)

Please, check the "send intro" option is not checked, maybe the value  was not saved correctly.

Send an image of your configuration to see how does it looks in your settings.

Try to do some tests, by create new save, test, edit again uncheck, save, test.

Could it be related to a sequence of mouse events and not to the option by itself.

Thou, I could not reproduce with any sequence I tried.

**Comment by hanspr** [comment] 2020-05-07 19:17
Ok, I managed to reproduce.

Still getting confused with version numbers and which branch in git to take.

In the master branch does not work.

Will be fixed when 6.2 is released, it works there.

Must have been a regression; I'm sure I fixed that many months back.

**Closed** 2020-05-10 09:09 UTC
Labels: bug

**Comment by hanspr** [comment] 2020-05-15 16:29
6.2 has been released, install check that it works.

If it works please close the ticket to clear the board.

**Comment by EduardMalik** [comment] 2020-05-18 08:21
> 6.2 has been released, install check that it works.
> 
> If it works please close the ticket to clear the board.
I check, it's work, thanks
