### ISSUE TITLE
(Snapshot Version 6) Folder appearance

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#306] opened 2019-12-12 17:00 UTC
**Is your feature request related to a problem? Please describe.**
I'm using new snapshot version 6, and having Groups and Subgroups is a bit messy now because all the folder listed are aligned, doesn't matter if is a main group or a subgroup, all are at the same level.

**Describe the solution you'd like**
Have a better hierarchy/alignment 

**Additional context**
See the attached picture:
![Screenshot from 2019-12-12 16-55-54](https://user-images.githubusercontent.com/1398552/70732725-e789e180-1d00-11ea-8344-140567c55ce4.png)

Thanks

**Comment by gfrenoy** [comment] 2019-12-12 19:11
This is indeed a "side effect" of the "compact tree" activity, see #133 

I would definitely prefer a more "structured" view but at this stage we have the mutually exclusive choices:
- less space but aligned
- structured but less compact
- completely rework the tree widget to have both a structured and compact tree

I guess the 3rd option would be the best but not sure who can do that work today...

**Comment by ferent** [comment] 2019-12-12 22:58
On my opinion, second option is my choice, having dozens subgroups makes difficult to find the servers you want to log in, and UX is key nowadays in interfaces. With current screens that have so much resolution nowadays, I don't think space is an issue, and having the option to change the font size for that menu, should be enough for anyone that wants to save some space. 

This is my personal opinion, and I will continue using this amazing software, just wanted to let you know that at least to me, organization is important when you need to deal with hundreds of servers. 

Thanks for the great effort you guys are doing.

**Comment by gfrenoy** [comment] 2019-12-14 09:54
Thanks for this opinion ; it really matters !

The rework made by @hanspr is really great ; we should now probably go to the next step.

Hopefully we can find someone that can look into this !

**Comment by hanspr** [comment] 2019-12-18 21:49
Hi @gfrenoy 

I looked some time back to this issue and the greatest challenge is the PACTree.pm module. It is very powerful and convenient, but it introduces the limitation that we all know. The way it works is that it ties 2 different structures together: A hash where all the connections are stored, and the gtk tree view object. The convinience is that you add/remove elements to the hash, and those are "magically" added, removed from the treeview. You receive a callback from the tree and the reference in the hash is there to know which connection has been selected, and so on.

Removing PACTree for another solution will be large rewrite because it is embedded in a lot of places in the code. And do not know any different model that could actually handle a large tree structure.

Tweaking PACTree to support cells inside a column, is beyond my knowledge, can not even tell if it is possible to actually do it.

But tweaking the interface, I could offer adding an option into the main configuration look and feel and allow a user to select from different models:

__Model one__, the current one, with the alignment issues. With 2 options?, aligned right or middle?

The original alignment, middle:

![imagen](https://user-images.githubusercontent.com/1572396/71125339-5c9b6200-21ac-11ea-97dd-8f346ca3178d.png)

The actual one, aligned right

![imagen](https://user-images.githubusercontent.com/1572396/71125941-84d79080-21ad-11ea-8ce3-3f13ff8f7c75.png)

 No matter what alignment we implement, there will be always one person that would not like it, and I understand, I do not like neither of them.

__Model 2__, a flat list, that is the must compact that you can get, would look similar to this

![imagen](https://user-images.githubusercontent.com/1572396/71123949-712a2b00-21a9-11ea-826e-e956b03ad6a8.png)

The opened folders would be bold and underlines, the closed folders non bold and normal. There is no way to indent in this model.

**Model 3**, I bring back the proposal of using utf8 icons. This requires noto-font to be installed. And I have kept playing with it and this is the current look that I use in my own tweaked local version.

![imagen](https://user-images.githubusercontent.com/1572396/71124078-b3ec0300-21a9-11ea-9723-cc749a8196ef.png)

Can not think of any other model based on the current implementation.

**Comment by ferent** [comment] 2019-12-18 22:24
@hanspr do you mean model 3 can be easily implemented? this model is perfect and look fantastic!! 

N.B.: Your screenshots shows your ssh connections in clear, I'd remove them and submit new ones with the content hidden :)

**Comment by hanspr** [comment] 2019-12-18 22:46
@ferent 

Model 3, was proposed on #133 but the problem is that icons are limited, depend on a specific font to work and icons are not editable (for now, I'm sure when the standard is finally accepted, we would be able to create our own set of icons, but currently it works with noto-font and is hard coded into the operating system).

At this stage, is extremely difficult to create your own font, tried for 3 weeks and desisted. And if you do, you have to replace noto-font.

The team, prefers images and icons that can be edited, that I can understand.

So, that is why I'm proposing to add options so the user can decide which model fits best to him/she.

**Comment by Mjolinir** [comment] 2020-01-02 14:21
I also like option #3, but shouldn't it use whatever icons are selected in the gtk3 theme, to maintain the look and feel of the other gtk3 apps in the environment?

**Comment by hanspr** [comment] 2020-01-02 14:50
@Mjolinir 

Sorry, I do not understand the comment. Maybe and image of some examples would make it clear to me.

**Comment by Mjolinir** [comment] 2020-01-02 15:05
> @Mjolinir
> 
> Sorry, I do not understand the comment. Maybe an image of some examples would make it clear to me.

In most Linux desktops, the user has the ability to choose what icons are used in gtk and/or qt apps. It is usually a setting one can make in the setting for the WM. See the following screenshot, this is where one would set the icons for gtk apps on KDE Plasma desktops. xfce4 and others have similar configuration options, and of course Gnome. 

![Screenshot3](https://user-images.githubusercontent.com/7074712/71673373-a0629f80-2d46-11ea-9ed6-eff9e67316ce.png)

My point is that Asbru should use the icons selected in the desktop configuration. KDE Plasma has specific settings for gtk apps, of course, because it is not gtk based. On native gtk DMs this would just be the default icons settings.

**Comment by hanspr** [comment] 2020-01-02 15:44
Hi @Mjolinir  

Perhaps I did not explain my self correctly, will try again.

There is only __one font__ available with color right now : NotoFontColor. No more, choosing a different one would render a black black font,  not what you see in my image. And from that font: only a characters have color, not all the characters are mapped to have color.

This is a page with the reference __font icons__ that can be used.

http://www.unicode.org/emoji/charts/full-emoji-list.html

This is what you get if you use a different font like awsome

![imagen](https://user-images.githubusercontent.com/1572396/68090311-f3e46a00-fe37-11e9-9f6d-ff3d309b32f3.png)

It could be feasible, to choose a font in Asbru, and the let you choose the characters you want to assign to each type of connection, which again at the moment do not know if it is worth it.

I do not think that using the Systems font has any thing to do with the proposed solution at this time. Again, maybe in the future when the standard of color fonts is defined, right now is experimental.

**Comment by Mjolinir** [comment] 2020-01-02 16:43
I think I must have misunderstood, not you. You were referring to the icons embedded into a font, not the actual icons in the WM. I have saw similar things like you are referring to with the powerline fonts used in some zsh themes. I'm sorry about my misunderstanding!

**Comment by hanspr** [comment] 2020-01-08 04:55
@gfrenoy 

Continuing with this discussion, I have read the information from Gtk3 TreeView, and I do not find any reference that tells me how (or even if it is possible) to attach 2 different render types into one single column, in this case a pixbuf and text render simultaneously in the same column, so they do not separate.

---

I still think that I can create 5 options with this layouts (or less if 5 is too much).

1.- Current icons and fonts

![imagen](https://user-images.githubusercontent.com/1572396/71128974-14803d80-21b4-11ea-8253-e42ed35d48f8.png)


2.- Expanders in text column

![imagen](https://user-images.githubusercontent.com/1572396/71950304-517c9600-319c-11ea-8c65-7e0fc1a6d015.png)

3.- No icons

![imagen](https://user-images.githubusercontent.com/1572396/71950253-30b44080-319c-11ea-9b08-26fa5db40549.png)

4.- Icons with Awesome font

![imagen](https://user-images.githubusercontent.com/1572396/68090311-f3e46a00-fe37-11e9-9f6d-ff3d309b32f3.png)

5.- Full colour utf8 icons

![imagen](https://user-images.githubusercontent.com/1572396/71129008-24981d00-21b4-11ea-87b0-80f57f7bfc66.png)

At least there would be options and we can close and stop more reports about this subject that comes back over and over. 

Or vote, everyone that is interested on this subject, please vote

:+1:  APPROVE having options
:-1:  WAIT to find another widget

@ferent , @Mjolinir , @hador , @beliys , @KlaasT , @figue , @merikz, @shapovalovanton, @wcasanova

**Comment by gfrenoy** [comment] 2020-01-08 22:16
If that choice would be available today, option 2 would be choice :)

That being said what we are looking at is something like this:
![image](https://user-images.githubusercontent.com/981546/72020257-afc47a00-326b-11ea-85ae-e9ff2767f97d.png)
(screenshot from https://dbeaver.io/ ; for those who did not try this great piece of software...please take some time to do so, really brillant !)

I don't see anything similar in the [Gtk Documentation](https://developer.gnome.org/gtkmm-tutorial/stable/sec-treeview-examples.html.en) and could not find any other example in any of the "plain Gtk" applications I'm using so at this stage, I'm just hoping I did not look it right and would wait that find a way to achieve what is required...

(only [my 2 cents](https://en.wikipedia.org/wiki/My_two_cents) !)

**Comment by merikz** [comment] 2020-01-08 23:43
Options, please. I'd probably use 3 "no Icons". I only use SSH connections, so it's either a group or a connection. No icons needed for that, the arrow indications for groups is enough. 
I really don't like the "current icons and fonts".

**Comment by hanspr** [comment] 2020-01-08 23:45
I use dbeaver, but that is build with java, and that widget I'm pretty sure is a java widget. I have finished reading all documentation of gtk treeview, it does not allow to have 2 cells in one column, so it is a dead end.

I can implement option 2 is very easy to modify the current master master branch to do that 3 new lines, that is all in PACMain.

But I also think that options would not harm anyone.

**Comment by hanspr** [comment] 2020-01-09 00:06
Please people come vote and write your comments. I believe is important to have a consensus on this. 

@ferent , @Mjolinir , @hador , @beliys , @KlaasT , @figue , @merikz, @shapovalovanton, @wcasanova

**Comment by figue** [comment] 2020-01-09 00:13
Implement options seems the best solution, but I understand the priorities and the time expended...
Keep 2 is good enough in the meantime, but 4 or 5 looks pretty for me.

**Comment by hanspr** [comment] 2020-01-09 00:17
Thanks for the comment @figue 

Place your vote on : https://github.com/asbru-cm/asbru-cm/issues/306#issuecomment-571890993

**Comment by x-wolverine-x** [comment] 2020-01-09 05:49
> @gfrenoy
> 
> Continuing with this discussion, I have read the information from Gtk3 TreeView, and I do not find any reference that tells me how (or even if it is possible) to attach 2 different render types into one single column, in this case a pixbuf and text render simultaneously in the same column, so they do not separate.
> 
> I still think that I can create 5 options with this layouts (or less if 5 is too much).
> 
> 1.- Current icons and fonts
> 
> ![imagen](https://user-images.githubusercontent.com/1572396/71128974-14803d80-21b4-11ea-8253-e42ed35d48f8.png)
> 
> 2.- Expanders in text column
> 
> ![imagen](https://user-images.githubusercontent.com/1572396/71950304-517c9600-319c-11ea-8c65-7e0fc1a6d015.png)
> 
> 3.- No icons
> 
> ![imagen](https://user-images.githubusercontent.com/1572396/71950253-30b44080-319c-11ea-9b08-26fa5db40549.png)
> 
> 4.- Icons with Awesome font
> 
> ![imagen](https://user-images.githubusercontent.com/1572396/68090311-f3e46a00-fe37-11e9-9f6d-ff3d309b32f3.png)
> 
> 5.- Full colour utf8 icons
> 
> ![imagen](https://user-images.githubusercontent.com/1572396/71129008-24981d00-21b4-11ea-87b0-80f57f7bfc66.png)
> 
> At least there would be options and we can close and stop more reports about this subject that comes back over and over.
> 
> Or vote, everyone that is interested on this subject, please vote
> 
> 👍 APPROVE having options
> 👎 WAIT to find another widget
> 
> @ferent , @Mjolinir , @hador , @beliys , @KlaasT , @figue , @merikz, @shapovalovanton, @wcasanova

Choice 2 should be the default, but 4 or 5 looks a way more "Awesome" for me.

**Comment by ferent** [comment] 2020-01-09 09:22
Choice 2 looks ok to me, and as @x-wolverine-x  said, 4 or 5 looks like the perfection if possible.

**Comment by nikuzz** [comment] 2020-01-09 10:39
I prefer 4 or 5

**Comment by beliys** [comment] 2020-01-09 12:00
Perhaps the ideal option would be to remove PACTree for another solution (I think in the future it will definitely be necessary to do this), but as a temporary solution you can make options, as in fact it is almost a ready solution. I like the 4 and 5 options the most.

**Comment by hanspr** [comment] 2020-01-09 15:33
@beliys 

>Perhaps the ideal option would be to remove PACTree for another solution (I think in the future it will definitely be necessary to do this), but as a temporary solution you can make options, as in fact it is almost a ready solution. I like the 4 and 5 options the most.

No doubt, first we need to find an alternative widget or a proposed alternative solution, and second a very long and hard migration. That current widget implementation is deeply rooted into the code.

**Comment by hanspr** [comment] 2020-01-09 15:47
@gfrenoy 

Give me the green light and can send a PR for the current branch or loki (or both) by the end of the weekend.

This does not mean that if we ever find a different widget or alternative solution to display the connections we would not implemented.

In any case any alternative widget or solution will remove this current widget and related completely, I could not see how to make 2 different implementations live together. And if it is not possible to get another widget or alternative, I'm sure that eventually the implementation of utf8 icons will become a standard, and then we would be able to accomplish the look that you are looking for.

**Comment by gfrenoy** [comment] 2020-01-09 20:57
@hanspr 

> I have finished reading all documentation of gtk treeview, it does not allow to have 2 cells in one column, so it is a dead end.

Can you look at the following code -> https://gist.github.com/gfrenoy/1bc5b89bdf42b8f19f5ac4ffc94368ea

It looks that this would achieve what we are looking for ; here is how it looks:
![image](https://user-images.githubusercontent.com/981546/72103211-09d74500-3329-11ea-92e8-7430c780e906.png)

The "trick" is to "pack" both renderers in the same column and then use "add_attributes" to specify the column of the store where the icon is defined.  I believe we can even do this with a custom icon (as a Gtk3::Gdk::Pixbuf)

That being said, I'm not yet sure where we can integrate this in Ásbrú, the way the connections tree is built is still a mystery to me but maybe you have an idea where we can find the text renderer and replace it with a "packed" one ?

(ps: thanks to "beast" and "muppet" for having that discussion in 2005 ;-p --> http://gtk.10911.n7.nabble.com/Mixed-pixbuf-and-text-td64176.html)

**Comment by wcasanova** [comment] 2020-01-09 21:34
option 2 and 3

**Comment by Mjolinir** [comment] 2020-01-09 22:14
> Choice 2 should be the default, but 4 or 5 looks a way more "Awesome" for me.

I agree, this would be my vote as well. Thank for the work you guys do, I really wish I had the skills to help more. I feel like a complainer, LOL

**Comment by hanspr** [comment] 2020-01-10 00:12
@gfrenoy 

Will check, hope I can port the logic to perl, I'm still to novice at gtk and its objects, I have barely learn to use its methods and understand the complicated way to place anything in a window.

**Comment by hanspr** [comment] 2020-01-10 01:20
@gfrenoy 

I checked out your code and unfortunately on this side we have PACTree.pm, that stands in the middle of the model and the TreeView. I do not see how to port that using pactree. If we use that approach we would have to recode everything again, meaning: All the code related to nodes : add, delete, rename, signal, copy, paste, etc.

Thou, I got a replay from perlmonks, that it might give me a light on how to solve it using pactree.

It will take me some time to experiment, all this stuff is too new to me.

**Comment by merikz** [comment] 2020-01-10 01:42
> It looks that this would achieve what we are looking for ; here is how it looks:
> ![image](https://user-images.githubusercontent.com/981546/72103211-09d74500-3329-11ea-92e8-7430c780e906.png)
> 
Yes, this is good! And then we don't need options; asbru had too many options already.

**Comment by mooky31** [comment] 2020-01-28 09:25
> It looks that this would achieve what we are looking for ; here is how it looks:
> ![image](https://user-images.githubusercontent.com/981546/72103211-09d74500-3329-11ea-92e8-7430c780e906.png)
 
Looks great, hope it will get committed 👍

**Comment by wcasanova** [comment] 2020-02-01 02:58
Thanks for the update, I look great ..
@hanspr

**Comment by hanspr** [comment] 2020-02-01 05:05
To anyone on this thread testing loki branch

__DO NOT CREATE OR EDIT CONNECTIONS !__ if the connection has a configured key file.

A regression was introduced on jump proxy code that will not save the key file, PR with correction has been sent, wait until is applied.

**Comment by gfrenoy** [comment] 2020-02-01 09:13
PR has been merged in loki.

Testers are welcome (see [instructions](https://github.com/asbru-cm/asbru-cm#testing-new-features)) but please make sure you have a safe copy of your configuration files (```~/.config/pac```) before using this **unsable** branch.

**Closed** 2020-02-01 15:51 UTC
Labels: enhancement, gtk3
