### ISSUE TITLE
asbru crashed, config file empty

### ISSUE THREAD

**Issue by The-Incubus** [asbru-cm/asbru-cm#265] opened 2019-11-07 09:05 UTC
**After a crash the config file is empty**
Asbru crashed and when i tried to restart it, it didn't.

**To Reproduce**
After opening and closing many connections, the interfaced becomes grey and unresponsive; close the window (don't just kill it). Restarting Asbru fails; the error shown in console is:
```
Ásbrú started (asbru-cm) with PID 21371
WARNING: Could not load config file '/home/MY_USER/.config/pac/pac.yml': 
INFO: Used config file '/home/MY_USER/.config/pac/pac.dumper'
not a reference at /opt/asbru/lib/PACMain.pm line 2974.
```
The config file is empty:
```
$ ls -l /home/MY_USER/.config/pac/pac.yml /home/MY_USER/.config/pac/pac.dumper
-rw-r--r-- 1 MY_USER MY_GROUP 0 Nov  6 17:08 /home/MY_USER/.config/pac/pac.dumper
-rw-r--r-- 1 MY_USER MY_GROUP 0 Nov  6 17:08 /home/MY_USER/.config/pac/pac.yml

```

**Expected behavior**
Config file not empty.
Asbru working.

**Desktop**
 - OS: Debian GNU/Linux 10 (buster)
 - Version: 5.2.1

**Comment by hanspr** [comment] 2019-11-07 16:13
Hi @The-Incubus 

* Asbru has way too many options. Please provide your settings options. Problem can happen with one combination of settings but not others : Tabs on external window, Tabs on main window, stand alone windows, clusters, autosave on or off, save on exit on or off, etc. Please share the images of your settings. Is best if you can take images of the settings so no one is omitted on my settings to try to reproduce.
* If you are able to reproduce the grey unresponsive window, take an image and try to describe the steps as precise as possible.
* For example:
   * How many is many is many connections, 2,4. I need to know so I don't stop at six when your exercise was at 10 or 20.
    * How do you interact:
    * open, open, open, open, open, close, open, close, close , close, close
    * open,close, open,close, open,close, open,close,open,close, open,close...
    * open, open, open, open, work working, for 10, 20 minutes, close, close, close
* What Asbru version are you using gtk3 branch or the main one.

If you are on the main branch try to move to the gtk3 branch, is very stable to my liking and if the problem is still there it would be fixed on this branch now. And then back ported if possible.

You will find the gtk3 branch and instructions to install in:

https://github.com/asbru-cm/asbru-cm/tree/gtk3

**Comment by The-Incubus** [comment] 2019-11-08 19:52
Hello,

  i've been using pac/asbru for 4 years and the crash has been there since then: it has never been a problem since when the config file got "delete" (God bless the backup): that's what this report is about.

To help you understand how I use it, I can say it's a pretty basic usage: I never detach tabs from the main window and I don't used the "cluster" mode. I have 4 or 5 ssh session running at the same time: sometimes just for a few minutes, sometimes for 2 or 3 hours. I always suspend my laptop so asbru is never closed and restarted (unless it crashes). During the years I have seen it "gone grey" many times: sometimes when I started a new ssh session (and it was the only one runnig) sometimes when when i started a few more than usual. All the crashes happened after many tabs have been opened or closed: I would say at least more than 50 but I've never spent time counting them. During the years i've changed 2 laptops so I don't think it's related to the hardware or the os (from debian 8 to 10, always "stable" branch)

Here are the screenshots of my configuration: the images are about what i've personalizaed, what is missing has default values.
https://gofile.io/?c=Z1tN0e
MD5: 6c59ceb59519ebcecdd95475943cd1cf

Thank you for pointing me to the gtk version: i'll give it a try.

Let me know if there's something more I can provide to help you find and this bug and thank you for continuting the work started with PAC.

**Comment by hanspr** [comment] 2019-11-08 20:04
@The-Incubus 

Thanks for the information, I will try to reproduce, meanwhile I would suggest that you install the new version in the gtk3 branch. We have solved many issues there, I use in a daily bases and I do not see any issues.

The instructions are on the main page I sent you before, but this is the transcript, it is very important that you install from "/gtk3/" as seen in the links below.

```
curl -s https://packagecloud.io/install/repositories/asbru-cm/gtk3/script.deb.sh | sudo bash
sudo apt-get install asbru-cm
```

**Comment by hanspr** [comment] 2019-11-08 20:23
I noticed from your images that you use Keepassx integration.

I have never used it. If you could disable that feature and include the login credentials directly in the terminal configuration, try that for a period and see if the issue goes away, to narrow down the possible cause.

**Comment by The-Incubus** [comment] 2019-11-08 22:20
I forgot to mention I'm running xfce4...

> @The-Incubus
> 
> Thanks for the information, I will try to reproduce, meanwhile I would suggest that you install the new version in the gtk3 branch. We have solved many issues there, I use in a daily bases and I do not see any issues.
> 
> The instructions are on the main page I sent you before, but this is the transcript, it is very important that you install from "/gtk3/" as seen in the links below.
> 
> ```
> curl -s https://packagecloud.io/install/repositories/asbru-cm/gtk3/script.deb.sh | sudo bash
> sudo apt-get install asbru-cm
> ```

I'm going to try the gtk3 version tomorrow.


> I noticed from your images that you use Keepassx integration.
> 
> I have never used it. If you could disable that feature and include the login credentials directly in the terminal configuration, try that for a period and see if the issue goes away, to narrow down the possible cause.

I'll give it a try: I started using keepass integration less than an year ago and the "grey" bug happened to me also before that.

If the gtk3 test doesn't go well, i'll ruin asbru with strace: maybe something usefull comes up :)


Thx again and good evening.

**Comment by gfrenoy** [comment] 2019-11-09 14:35
Just a kind reminder, let's try to stay focus on a single topic per issue.  Here, I believe we should stay focus on finding the root reason of the file corruption.

This can only happen if you have a crash while the file configuration is overwritten.

Were you changing connection settings or preferences when the crash happened ?

**Comment by The-Incubus** [comment] 2019-11-09 15:26
@gfrenoy 
No. I was starting a new ssh connection and asbru become grey and unresponsive. I closed it like i normally do (pressing the X): it didn't ask to save any changes.

**Comment by gfrenoy** [comment] 2019-11-09 15:30
And as you are not configured on "auto save", I've the feeling the file may have been corrupt even before it crashes ... At least, I do see the relationship between those two events :-/

**Comment by hanspr** [comment] 2019-11-30 21:01
Hi, @The-Incubus 

We released the modifications in the gkt3 branch to recover a lost pac.yml file in case of a crash, and the fix for xfce4 sudden disconections bug has been applied too, maybe this was the source of your crashes.

So you should be able to use the gtk3 branch now without any problems and not loose any pac.yml file again.

If you agree with the solution, please tell us so we can close this issue. In case you still experience unexpected crashes, then I would recommend that you open a new issue with specific information about the crash.

Thanks for your help.

**Closed** 2019-12-30 22:24 UTC
Labels: awaiting feedback
