### ISSUE TITLE
"Select key bindings to disable from TABs Window" not working for  "alt-p".

### ISSUE THREAD

**Issue by misiektw** [asbru-cm/asbru-cm#590] opened 2020-04-28 11:07 UTC
**Describe the bug**
Even after "select key bindings to disable from TABs Window" are all set to 'checked' shortcut alt-p still opens Preferences window instead of being passed to terminal.

**To Reproduce**
1. Open preferences, check "ALT" in "Select keybindings to diable". Save and close.
2. Open connection to server, and press alt-p
3. Preferences pop up

**Expected behavior**
alt-p should be passed to terminal. (previous command in midnight commander in my case)

**Environment (please complete the following information):**
 - OS:  Arch
 - Ásbrú Version 6.1.2

**Comment by hanspr** [comment] 2020-04-28 16:02
Hi @misiektw 

The problem is that you might be disabling in the "Main Preferences" and those settings are useless.

![imagen](https://user-images.githubusercontent.com/1572396/80509513-27173a00-893f-11ea-948b-b34d14ce5cfd.png)

You need to disable in each particular "Terminal settings".

![imagen](https://user-images.githubusercontent.com/1572396/80509563-34ccbf80-893f-11ea-9cc3-c5822f67f9ee.png)

All this logic will be removed with #556 , because is wrong and does not allow to customize keybindings.

I already finished the solution, but I'm still waiting for the main 6.2 version to be released and then I will be able to send the changes to loki for testers.

Follow #556 if you want to know when will the push request is merged and test using the builds from the loki branch. Or do it with the current work around explained above.

**Comment by misiektw** [comment] 2020-04-28 16:14
I didn't notice this options in individual connections, however it changes nothing. I just tried it. Still alt-p opens preferences instead going into terminal.

However if keybinding remapping will be available soon, then this is pretty much non-issue. I just hope it will be possible to turn them all off....

**Comment by hanspr** [comment] 2020-04-28 17:17
> I didn't notice this options in individual connections, however it changes nothing.

That keybind is embedded in the button creation and is controlled directly by gtk.

```perl
$$self{_GUI}{configBtn} = Gtk3::Button->new_with_mnemonic('_Preferences');
```

As was not aware of this types of bindings, good to know.

I will send a PR, to remove all this embedded bindings in 6.2, they add even less control to the current keybinds model. And will not be able to be customizable.

**Closed** 2020-05-10 09:07 UTC
Labels: bug
