### ISSUE TITLE
'Favourites'/'History'/'Clusters' tab label gets lost sometimes

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#230] opened 2019-10-19 09:51 UTC
Make the left-side bar a bit wider, so that the buttons `Connections`/`Favourites`/`History`/`Clusters` don't need scrolling arrows. This is not necessary to trigger the bug, but makes it easier to see what happens.

Under some circumstances, the label goes back to say `Connections` on the first tab, although another tab is selected.

I found two ways to reproduce it.

1\. Define a new terminal-based connection (e.g. local shell: Generic Command: bash). Launch it for the first time. Quickly click on one of the `Favourites`/`History`/`Clusters` tabs. Wait for about a second for the bug to occur.

(Since it only happens when the connection is launched for the first time, and then with a slight delay, I'm wondering if it's related to taking the screenshot.)

2\. Launch the connection two or more times. Click (you don't have to hurry this time) on one of the `Favourites`/`History`/`Clusters` buttons. Click on the `X` (close) button on a non-visible terminal's tab.

**Comment by gfrenoy** [comment] 2019-12-01 22:04
Interesting :)

I found a third way to reproduce that might be even easier:
- select the ```Clusters``` tab
![image](https://user-images.githubusercontent.com/981546/69921033-dcc48680-148e-11ea-84cb-29640f9ecd3c.png)
- create and close a local shell
- Strangely enough, the focus is still on ```Clusters``` but the text of the ```Connections``` tab is shown:
![image](https://user-images.githubusercontent.com/981546/69921007-9a02ae80-148e-11ea-82ad-a3271b10a785.png)

Probably not a big deal but if one is curious ... understanding the root reason might be funny :)

**Comment by gfrenoy** [comment] 2020-05-24 15:39
Made a bit more investigations on this.  The "glitch" happens when a tab is removed from the main notebook:

https://github.com/asbru-cm/asbru-cm/blob/6.2.0/lib/PACTerminal.pm#L541

Not sure why changing something in one notebook would affect another notebook... There's nothing in the code I can see that would do anything with that event so at this stage, I would assume the problem is located in Gtk3.

If I test the same on a more recent version (tested on Ubuntu 20.04 focal), the problem has disappeared.

I would guess we can close this.

**Closed** 2020-06-01 12:34 UTC
Labels: bug
