### ISSUE TITLE
asbru crash after manual RDP session disconnection

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#538] opened 2020-03-30 15:29 UTC
any RDP session on rdesktop makes crash asbru if I right click on connection tabs and choose disconnect session. reproducible on last stable and also on loki branch

**Comment by popxunga** [comment] 2020-03-30 17:07
BTW, this is the error on crash (on EL7):

(asbru-cm:5158): Gdk-ERROR **: 18:05:58.409: The program 'asbru-cm' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 828997 error_code 3 request_code 131 (XInputExtension) minor_code 40)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

[1]+  Trace/breakpoint trap   (core dumped) asbru-cm

**Comment by gfrenoy** [comment] 2020-03-31 07:22
@vibo69 Would you mind using the bug template ?  In particular, what OS are you running with ?

As a matter, I cannot reproduce it on my Ubuntu 18.04 system nor on a plain CentOS 7 VM.

**Comment by vibo69** [comment] 2020-03-31 07:45
`$ asbru-cm --verbose
INFO: Ásbrú Connection Manager 6.2.0 (asbru-cm) started with PID 29234
INFO: Desktop environment detected : xfce
INFO: Config directory is '/home/vibo/.config/pac'
INFO: Used config file '/home/vibo/.config/pac/pac.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.54
       - has_bright = 1
       - major_version = 0
       - minor_version = 54
       - vte_feed_binary = 1
       - vte_feed_child = 1
INFO: Theme directory is '/opt/asbru/res/themes/default'
INFO: Using Gnome tray icon
DEBUG: Starting window position = (maximized, maximized} ; window size (maximized, maximized)
Use of uninitialized value in concatenation (.) or string at /opt/asbru/lib/PACUtils.pm line 1438.

(asbru-cm:29234): Gdk-ERROR **: 09:43:25.115: The program 'asbru-cm' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 119204 error_code 3 request_code 131 (XInputExtension) minor_code 40)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap

$ cat /etc/*rele*
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

**Comment by gfrenoy** [comment] 2020-03-31 09:01
Yes with Debian 10 + xfce, I can reproduce the problem.

@popxunga Are you also using xfce on your EL7 ?

**Comment by popxunga** [comment] 2020-03-31 09:04
> Yes with Debian 10 + xfce, I can reproduce the problem.
> 
> @popxunga Are you also using xfce on your EL7 ?

@gfrenoy ... RHEL 7.7 with gnome3 here.

**Comment by gfrenoy** [comment] 2020-06-01 12:33
I believe I found out the root issue and was able to find workaround: the RDP window needs to be hidden before disconnecting the connection.

The fix is available on the loki branch, let us know if it fixes the issue for you.

**Comment by popxunga** [comment] 2020-06-01 17:16
Hi @gfrenoy ...

I'm currently unable to install the latest loki build due to dependency issues:
Resolving Dependencies
--> Running transaction check
---> Package asbru-cm.noarch 0:6.3.0~1590344834-1.el7 will be updated
---> Package asbru-cm.noarch 0:6.3.0~1591014959-1.el7 will be an update
--> Processing Dependency: perl(Gtk3::TreeView) for package: asbru-cm-6.3.0~1591014959-1.el7.noarch
--> Finished Dependency Resolution
Error: Package: asbru-cm-6.3.0~1591014959-1.el7.noarch (rhel7-xxx-xxx-xxx)
           Requires: perl(Gtk3::TreeView)
 You could try using --skip-broken to work around the problem

At the moment I'm not sure where to get the missing library. Any idea  ?
Thanks.

**Comment by gfrenoy** [comment] 2020-06-01 20:48
Mm?  Very surprising !

`Gtk3::TreeView` is supposed to be provided by `perl-Gtk3` so there is no reason to have a specific package for this.

And moreover, we don't have this requirements in our [spec file](https://github.com/asbru-cm/asbru-cm/blob/d8686aa638b6734403f218369208ef247083cf52/dist/rpm/asbru.spec)...

I would believe the rpm packaging system is trying to be clever and saw that change:

https://github.com/asbru-cm/asbru-cm/commit/580367fe423ef61526517027be0ccdc49e66a219#diff-a1cfee7728b9037161906e720415bcb1L11

and thought it requires an additional package `Gtk3::TreeView`.

Let me see how I can convince that beast to leave me the control on the requirements...

**Comment by popxunga** [comment] 2020-06-01 21:43
Hi @gfrenoy 
I was able to successfully Install the loki build after the 2nd attemp of #538.
Tested the disconnect from Tab context menu in one RDP connection and it worked fine, no crash :-)
Thanks for your support.

**Comment by gfrenoy** [comment] 2020-06-01 21:49
Wonderful !

Thanks to you for always being the first one to try the "bleeding edge" features, your contribution is very much appreciated :sunglasses:

Let me also know if this eventually fixed this issue/crash :boom:

**Comment by popxunga** [comment] 2020-06-01 22:10
Yes ... you probably didn't notice it, but I wrote that I tested the disconnect from the RDP tab context menu and it worked fine. So, the crash issue is fixed as well :-)

**Comment by gfrenoy** [comment] 2020-06-01 22:24
Indeed, I read a bit too fast your last message !

So it's a double "Wonderful !" that you get :)

**Closed** 2020-06-11 12:43 UTC
Labels: awaiting feedback, bug
