### ISSUE TITLE
Blank main window when starting iconified

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#783] opened 2021-02-23 18:34 UTC
Hi ...
After installing either 6.3.1 or 6.4.0 latest build, the main Asbru window is just a totally gray rectangle.
Tested on CentOS 8 and RHEL 8.
Can you check it please ?
Thanks.

**Comment by alperencaliskan** [comment] 2021-02-24 13:05
Same for me. 6.3.0 works, 6.3.1 doesn't.
OS: LinuxMint 20.1

Terminal log
```
INFO: Ásbrú Connection Manager 6.3.1 (asbru-cm) started with PID 90288
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : cinnamon
INFO: Config directory is '/home/user/.config/asbru'
INFO: Used config file '/home/user/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.60
INFO: Theme directory is '/opt/asbru/res/themes/default'
INFO: Using Gnome tray icon
WARN: Adding new keybinding [Ctrl+Return] for [Terminal]/[Start Terminal]...
WARN: Adding new keybinding [Ctrl+plus] for [Terminal]/[Zoom in text]...
WARN: Adding new keybinding [Alt+n] for [Terminal]/[Show/Hide connections list]...
WARN: Adding new keybinding [Ctrl+d] for [Connections Tree]/[Clone connection]...
WARN: Adding new keybinding [Alt+e] for [Favourites Tree]/[Edit selected node]...
WARN: Adding new keybinding [undef-infotab] for [Tabs]/[Got to Info Tab]...
WARN: Adding new keybinding [AltCtrl+x] for [Terminal]/[Reset Terminal]...
WARN: Adding new keybinding [Alt+r] for [Connections Tree]/[Toggle protection]...
WARN: Adding new keybinding [Ctrl+f] for [Connections Tree]/[Find in connection tree]...
WARN: Adding new keybinding [Ctrl+t] for [Connections Tree]/[Collaps tree completly]...
WARN: Adding new keybinding [Ctrl+Page_Down] for [Tabs]/[Next Tab]...
WARN: Adding new keybinding [Ctrl+minus] for [Terminal]/[Zoom out text]...
WARN: Adding new keybinding [AltCtrl+X] for [Terminal]/[Reset Terminal and Clear window]...
WARN: Adding new keybinding [Ctrl+r] for [Connections Tree]/[Expand tree completly]...
WARN: Adding new keybinding [Alt+f] for [Connections Tree]/[Add connection to favourites]...
WARN: Adding new keybinding [Ctrl+W] for [Terminal]/[Disconnect Terminal]...
WARN: Adding new keybinding [Ctrl+f] for [Main Window]/[Find in connection tree]...
WARN: Adding new keybinding [Ctrl+F4] for [Tabs]/[Close current Tab]...
WARN: Adding new keybinding [Ctrl+C] for [Terminal]/[Copy selection to clipboard]...
WARN: Adding new keybinding [Ctrl+f] for [Terminal]/[Find in connection tree]...
WARN: Adding new keybinding [Alt+e] for [History Tree]/[Edit selected node]...
WARN: Adding new keybinding [CtrlAlt+r] for [Terminal]/[Remove terminal from cluster]...
WARN: Adding new keybinding [F11] for [Terminal]/[Go full screen]...
WARN: Adding new keybinding [F2] for [Connections Tree]/[Rename node]...
WARN: Adding new keybinding [Ctrl+x] for [Connections Tree]/[Cut node]...
WARN: Adding new keybinding [Ctrl+Tab] for [Tabs]/[Last focused Tab]...
WARN: Adding new keybinding [Ctrl+b] for [Terminal]/[Paste and regex delete]...
WARN: Adding new keybinding [Alt+F] for [Favourites Tree]/[Remove connection from favourites]...
WARN: Adding new keybinding [Alt+n] for [Main Window]/[Show/Hide connections list]...
WARN: Adding new keybinding [Ctrl+ampersand] for [Terminal]/[Send Cisco interrupt keypress]...
WARN: Adding new keybinding [Alt+c] for [Connections Tree]/[Connect selected node]...
WARN: Adding new keybinding [Ctrl+T] for [Main Window]/[Open a local shell]...
WARN: Adding new keybinding [Ctrl+D] for [Terminal]/[Duplicate connection]...
WARN: Adding new keybinding [Ctrl+q] for [Main Window]/[Exit Ásbrú]...
WARN: Adding new keybinding [Ctrl+F3] for [Terminal]/[Find Terminal]...
WARN: Adding new keybinding [Ctrl+Page_Up] for [Tabs]/[Previous Tab]...
WARN: Adding new keybinding [Ctrl+g] for [Terminal]/[Guess hostname]...
WARN: Adding new keybinding [AltCtrl+s] for [Terminal]/[Open SFTP session]...
WARN: Adding new keybinding [Ctrl+p] for [Terminal]/[Paste terminal password]...
WARN: Adding new keybinding [Shift+Insert] for [Terminal]/[Paste selection into terminal]...
WARN: Adding new keybinding [Ctrl+w] for [Terminal]/[Close Terminal]...
WARN: Adding new keybinding [Alt+e] for [Terminal]/[Edit Connection]...
WARN: Adding new keybinding [Alt+F] for [Connections Tree]/[Remove connection from favourites]...
WARN: Adding new keybinding [Alt+e] for [Connections Tree]/[Edit selected node]...
WARN: Adding new keybinding [Ctrl+I] for [Terminal]/[Show the Info tab]...
WARN: Adding new keybinding [Ctrl+V] for [Terminal]/[Paste clipboard into terminal]...
WARN: Adding new keybinding [Ctrl+v] for [Connections Tree]/[Paste node]...
WARN: Adding new keybinding [Ctrl+N] for [Terminal]/[Close disconnected sessions]...
WARN: Adding new keybinding [Ctrl+0] for [Terminal]/[Zoom reset text]...
WARN: Adding new keybinding [Ctrl+R] for [Terminal]/[Restart connection (close and start)]...
WARN: Adding new keybinding [Ctrl+q] for [Terminal]/[Exit Ásbrú]...
WARN: Adding new keybinding [Ctrl+c] for [Connections Tree]/[Copy node]...
WARN: Adding new keybinding [Alt+e] for [Clusters Tree]/[Edit selected node]...
WARN: Adding new keybinding [CtrlShift+F4] for [Terminal]/[Close all tabs]...

```
![image](https://user-images.githubusercontent.com/9333745/109004325-b1444200-76b9-11eb-86cd-720088f0a3a3.png)

**Comment by albertocrj** [comment] 2021-02-24 14:52
Same for me in fedora32.

**Comment by misog-git** [comment] 2021-02-24 21:43
Same for me in Ubuntu 20.04.2
The terminal log is similar as @alperencaliskan, but I don't get any "WARN: Adding new keybinding...." line

**Comment by gfrenoy** [comment] 2021-02-24 21:45
Ouch this looks bad !  Sorry about that.  Does this happen on a new configuration or with existing configuration ?

**Comment by popxunga** [comment] 2021-02-24 21:57
@gfrenoy  ... it doesn't happen if it is a clean install.
Just tested it by moving the ~/.config/asbru folder to something else.

**Comment by gfrenoy** [comment] 2021-02-24 22:01
@popxunga ah, thanks, that's why I was not able to reproduce this :-/

I played around with the options and I believe this only happens when you "iconified at startup" checked ?  Can you try to uncheck it ?  Right-clicking on the tray icon should give you access to the preferences.

**Comment by popxunga** [comment] 2021-02-24 22:09
@gfrenoy ... yes, I can reproduce the issue on a new install by checking the "iconified at startup" option on Global Preferences.

**Comment by gfrenoy** [comment] 2021-02-24 22:23
Just pushed a commit on both branches.  When the builds are done (approx. in 30 minutes), can someone test the snapshot or loki release ?  If the fix is confirmed to work, I'll release a v6.3.2 very soon.

Thanks all for your feedback and extended explanations.

**Comment by popxunga** [comment] 2021-02-24 23:13
Just tested latest loki build. It is better but still not perfect.
During Asbru startup, the Main window is now briefly shown (for less than a second) before it gets iconified on systray.

**Comment by gfrenoy** [comment] 2021-02-24 23:23
Mmm, here I do not even notifice the difference, ... you should get a faster CPU :-p
Just kidding, I understand why ; need to think a bit more about the proper way to handle this.

**Comment by gfrenoy** [comment] 2021-02-25 22:32
Just made a few changes that should go into the right direction but according to my tests, if you have some terminals launched at startup, you may still experience a quick display of the main window...

Let me know if it works good enough for you so that I can close this issue and initiate 6.3.2 release.

**Comment by popxunga** [comment] 2021-02-26 08:40
Hi @gfrenoy 
Yes ... this [commit](https://github.com/asbru-cm/asbru-cm/commit/eb7458226287b1d4dee760ac1b6b0d479b0ab95f) fixed the issue (I do not have any terminals launched on startup).
Thanks for your support.

**Closed** 2021-02-27 08:52 UTC
Labels: bug
