### ISSUE TITLE
Power Cluster Controller   Explode  Send to ALL terminal  doesn't work anymore

### ISSUE THREAD

**Issue by xattack** [asbru-cm/asbru-cm#775] opened 2021-02-17 00:18 UTC
**Describe the bug**

   If you try to explode several terminals / tabs when working with Asbru v6.3.0 , it doesn't work anymore 

**To Reproduce**
1. Open Asbru 
2.Click on several already registered servers and then try to use PCC to explode them 
3. Doesn't work 

**Expected behavior**
   
     See the exploded windows on your screen 

**Screenshots**

![Screenshot from 2021-02-16 18-12-46](https://user-images.githubusercontent.com/8902460/108138261-3b215900-7083-11eb-97fd-f031c61fab20.png)

**Environment (please complete the following information):**
 - OS:  Linux Mint 19.3 Tricia
 - Ásbrú Version 6.3.0

**Comment by gfrenoy** [comment] 2021-02-17 17:56
> Click on several already registered servers and then try to use PCC to explode them

Can you elaborate a little bit more, I don't understand what you mean and cannot reproduce the issue.

Thanks.

**Comment by xattack** [comment] 2021-02-17 22:29
Shure . This is the situation for me . After upgraded Asbru to version 6.3.0. PCC stop working properly. 

Sometimes i do some adjustment over the configuration of some servers , in this case there were four server , in order to do it simultaneously , I'm using PCC, so i can send the same order to all of them at the same time. But after last upgrade , in my laptop and OS , Asbru stop working properly, so when using the option send to all in PCC and click on explode sometimes it's just one of the four tabs i'm working with , could be more or less , it doesn't matter, just one explode and the other stay attached to the window or the other situation is when none of them explode.

In order to debbug some more , from the command line , started Asbru , but could not see much more information 

  
![Screenshot from 2021-02-16 18-23-22](https://user-images.githubusercontent.com/8902460/108276170-0376e780-713d-11eb-9737-0832695c59f9.png)

![Screenshot from 2021-02-16 18-24-28](https://user-images.githubusercontent.com/8902460/108276183-096cc880-713d-11eb-830f-64f80ac0b29f.png)

It says it can't call some method in PACPCC.pm

**Comment by gfrenoy** [comment] 2021-02-17 22:46
Thanks for the additional information.  I've been able to reproduce the problem.  Still need to understand the root reason (and fix it...).

**Comment by gfrenoy** [comment] 2021-02-17 23:27
Thanks again for your great feedback.  The last commit should fix the issue.  It will be released with 6.3.1.  You can already give it a try in our "snapshots" builds.

**Closed** 2021-02-18 20:56 UTC
Labels: bug
