### ISSUE TITLE
[gtk3] It doesn't close, the windows

### ISSUE THREAD

**Issue by B1tl0rd** [asbru-cm/asbru-cm#259] opened 2019-11-01 12:14 UTC
**Describe the bug**
Hello friends, there is an error, when you open any connection, then they cannot close, it simply does nothing.

If I drag the window in a decoupled way, it can float like a single terminal. if you close the connection ..
**Screenshots**
![image](https://user-images.githubusercontent.com/12401985/68024217-37987180-fc88-11e9-88bd-836fe5b58bd2.png)

![image](https://user-images.githubusercontent.com/12401985/68024365-ae356f00-fc88-11e9-90e4-130aff08b56e.png)

**Desktop (please complete the following information):**
- OS: ArchLinux
- DE: Plasma
- vte3: 0.58.2
- perl-gtk3: 0.035

**Comment by gfrenoy** [comment] 2019-11-03 11:23
> when you open any connection, then they cannot close, it simply does nothing.

I remember a very similar issue in the early version of the GTK3 branch.

Can you confirm you are using a recent version of the code ?

**Comment by B1tl0rd** [comment] 2019-11-03 11:32
@gfrenoy 
If last version, there are several bugs, to be able to close the connections, you have to undock them, and there if they close, but it is not so because they are open as in the background. Touch kill processes manually.

**Comment by gfrenoy** [comment] 2019-11-03 11:42
Which version (commit hash) are you using ?

**Comment by B1tl0rd** [comment] 2019-11-03 12:09
1e17c55046182a7c6bfde6b281c7265d38e2e448

**Comment by gfrenoy** [comment] 2019-11-03 12:21
> 1e17c55046182a7c6bfde6b281c7265d38e2e448

Mmm, this is not a commit from the Ásbrú project :-/

If I got it correctly, you're using this repository : https://aur.archlinux.org/cgit/aur.git/?h=asbru-cm-gtk3-git

This is quite "obsolete" today since lots of change are happening today.  We cannot support that, sorry.

I would first suggest to use the latest version ; it should work fine (at least it is for me...).

@figue Can you maybe help with an update of your Arch repository ?

**Comment by B1tl0rd** [comment] 2019-11-03 12:24
how strange the PKGBUILD points to the official version ..

 Maintainer: Joan Figueras <ffigue at gmail dot com>
# Contributor: Luca Contini <jkd[dot]luca[at]gmail[dot]com>

pkgname=asbru-cm-gtk3-git
_pkgname=${pkgname%-gtk3-git}
pkgver=6.0.0
pkgrel=1
arch=('any')
license=('GPL3')
pkgdesc="A free and open-source connection manager. GTK3 depelopment branch. GIT version"
url="https://github.com/asbru-cm/asbru-cm"
depends=('perl' 'vte3' 'cairo-perl' 'glib-perl' 'pango-perl' 'perl-socket6' 'perl-expect' 'perl-yaml' 'perl-crypt-cbc' 'perl-crypt-blowfish' 'perl-gtk3' 'perl-net-arp' 'uuid' 'openssh' 'inetutils' 'perl-crypt-rijndael' 'perl-xml-parser' 'libcanberra' 'perl-gtk3-simplelist' 'libwnck3' 'perl-io-stty' 'perl-io-tty')
optdepends=('uucp: Unix-to-Unix Copy' 'rdesktop: RDP connections' 'freerdp: RDP connections' 'openssh: SSH connections' 'mosh: Mobile shell' 'tigervnc: for VNC connections'
	    'perl-x11-guitest: To fit perfectly RDP tabs')
makedepends=('git')
#conflicts=()
source=("git+https://github.com/asbru-cm/asbru-cm.git#branch=gtk3" asbru-cm-gtk3.desktop)
sha256sums=('SKIP'
            '2a79176347ca05ae465ee9c6e64b252d67dc3cfb6d1df92b1cfb9b0b731c2561')

package() {
	cd ${srcdir}/${_pkgname}
	mkdir -p $pkgdir/{opt/asbru-gtk3,usr/share/pixmaps,usr/share/man/man1,usr/share/applications,usr/bin,etc/bash_completion.d}
	cp -rp res utils lib $pkgdir/opt/asbru-gtk3/
	cp -p res/asbru_bash_completion $pkgdir/etc/bash_completion.d/asbru_gtk3_bash_completion
	cp res/asbru-logo-64.png $pkgdir/usr/share/pixmaps/${_pkgname}-gtk3.png
	cp ${srcdir}/asbru-cm-gtk3.desktop $pkgdir/usr/share/applications/
	gzip -c res/${_pkgname}.1 > $pkgdir/usr/share/man/man1/${_pkgname}-gtk3.1.gz
	cp -p ${_pkgname} $pkgdir/opt/asbru-gtk3/${_pkgname}
	chmod 755 $pkgdir/opt/asbru-gtk3/${_pkgname}
	ln -sf /opt/asbru-gtk3/${_pkgname} $pkgdir/usr/bin/${_pkgname}-gtk3
}

**Comment by figue** [comment] 2019-11-03 21:18
When you build the package, makepkg (Archlinux tool to build packages) pull always latest version, in this case, from gtk3 branch. Any package that pulls directly from git does that. In AUR webpage the package only reflects the latest commit that was in the time it was pushed.

Let me show a standard package building (the f forces the instalation, is needed to replace git packages):
```
$ env LC_ALL=C makepkg -sicf
==> Making package: asbru-cm-gtk3-git 6.0.0-1 (Sun Nov  3 22:11:27 2019)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating asbru-cm git repo...
Fetching origin
  -> Found asbru-cm-gtk3.desktop
==> Validating source files with sha256sums...
    asbru-cm ... Skipped
    asbru-cm-gtk3.desktop ... Passed
==> Extracting sources...
  -> Creating working copy of asbru-cm git repo...
Reset branch 'makepkg'
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "asbru-cm-gtk3-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: asbru-cm-gtk3-git 6.0.0-1 (Sun Nov  3 22:11:29 2019)
==> Installing package asbru-cm-gtk3-git with pacman -U...
loading packages...
warning: asbru-cm-gtk3-git-6.0.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)        Old Version  New Version  Net Change

asbru-cm-gtk3-git  6.0.0-1      6.0.0-1        0.00 MiB

Total Installed Size:  2.81 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring       [-----------------------------------------] 100%
(1/1) checking package integrity       [-----------------------------------------] 100%
(1/1) loading package files       [-----------------------------------------] 100%
(1/1) checking for file conflicts       [-----------------------------------------] 100%
(1/1) checking available disk space       [-----------------------------------------] 100%
:: Processing package changes...
(1/1) reinstalling asbru-cm-gtk3-git       [-----------------------------------------] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating the desktop file MIME type cache...
==> Cleaning up...

Then, in same directory, you can find the git repo used in directory "asbru-cm", so to see a describe simply execute:
```
$ git --git-dir=asbru-cm describe --long --tags  
5.2.1-0-g1687e82
```

**Comment by B1tl0rd** [comment] 2019-11-03 21:51
if it is okay. It was my mistake in the calculation of git hash.
![image](https://user-images.githubusercontent.com/12401985/68092514-ce248880-fe6a-11e9-9c01-c73193de2bf0.png)

**Comment by KlaasT** [comment] 2019-11-03 21:54
Is it possible that you have checked out master and not the gtk3 branch?

On master the latest release is 5.2.1

**Comment by figue** [comment] 2019-11-04 00:36
If you did right, makepkg will checkout gtk3 branch.

Launch makepkg with -C again and without -c to keep source files, then see into src:
```
$ makepkg -sCf
$ cd src/asbru-cm
$ git branch -v
* makepkg c4c2ab4 Add pcc tray menu (#258)
  master  1687e82 Updated Changelog
$ git describe --long --tags
5.2.0-126-gc4c2ab4
```
In makepkg internals, it clones gtk3 branch as is declared in source array:
```
$ grep ^source PKGBUILD
source=("git+https://github.com/asbru-cm/asbru-cm.git#**branch=gtk3**" asbru-cm-gtk3.desktop)
```
then it checkout this branch to a new branch called "makepkg" that finally is cloned into src directory. Then all files in that directory are copied to final package.

**Comment by B1tl0rd** [comment] 2019-11-04 10:45
ok, . Everything is fine with the branch and hash of the commit. despite the last change I still have the same problem .. even delete the directory ~ / .config / pac, but I still have the same problem

![image](https://user-images.githubusercontent.com/12401985/68115226-a539dd00-fed6-11e9-9dfd-05f81b7afe37.png)

@figue Do you get the same mistake?

**Comment by figue** [comment] 2019-11-04 11:59
No, Ásbrú is working fine.

Probably you have an old perl package you need to rebuild. Execute: pacman -Qqo '/usr/lib/perl5/vendor_perl'

When you use pacman don't you see any warning about old perl packages?

**Comment by B1tl0rd** [comment] 2019-11-04 13:51
pacman -Qqo '/usr/lib/perl5/5.30/vendor_perl' >> perl
pacman -Qqo '/usr/share/perl5/vendor_perl/' >> perl

rebuild all. same problem..
I uninstalled everything, and reinstalled ... I'll do other tests anyway ...
: - /

![asbru](https://user-images.githubusercontent.com/12401985/68124937-3b79fd00-feef-11e9-8e32-60a62c7bcab2.png)

**Comment by panciom** [comment] 2019-11-04 14:04
Hello to everyone and thanks to all for the gtk3 version of asbru-cm.

I have the same issue (and others ;-D)...

Debian/SID regularly updated.
Asbru-CM downloaded from package-cloud (i have to write buster inside the script).

If i detach the console windows then i can close.

I will update to latest git and let you know.

Thanks as always.
Mirko

**Comment by panciom** [comment] 2019-11-04 16:00
Hello.
I have downloaded latest git with:
`git clone -b gtk3 https://github.com/asbru-cm/asbru-cm.git`

Started with ./asbru-cm inside dir created.

Bug closing console window still present.

On console i see these:
> 
> *** unhandled exception in callback:
> ***   need an array ref to convert to GArray at /home/pancio/asbru-cm/lib/PACUtils.pm line 3847.
> ***  ignoring at /usr/share/perl5/Gtk3.pm line 572.

Thanks
Mirko

**Comment by figue** [comment] 2019-11-04 16:18
> pacman -Qqo '/usr/lib/perl5/5.30/vendor_perl' >> perl
> pacman -Qqo '/usr/share/perl5/vendor_perl/' >> perl
> 
> rebuild all. same problem..
> I uninstalled everything, and reinstalled ... I'll do other tests anyway ...
> : - /
> 
> ![asbru](https://user-images.githubusercontent.com/12401985/68124937-3b79fd00-feef-11e9-8e32-60a62c7bcab2.png)
> 
> ![image](https://user-images.githubusercontent.com/12401985/68126003-957bc200-fef1-11e9-9115-1dc5009e35d5.png)

Sorry... I think that output was because Ásbrú doesn't work for you...

Yes: I can confirm that now Ásbrú doesn't close tabs or app. I can see these in console:
```
~ $ LC_ALL=C asbru-cm-gtk3 
INFO: Ásbrú started (asbru-cm-gtk3) with PID 3847
INFO: Using config directory '/home/figue/.config/pac'
INFO: Used config file '/home/figue/.config/pac/pac.nfreeze'
INFO: Using Gnome tray icon
Argument "button" isn't numeric in subroutine entry at /usr/lib/perl5/5.30/vendor_perl/Glib/Object/Introspection.pm line 67.
*** unhandled exception in callback:
***   need an array ref to convert to GArray at /opt/asbru-gtk3/lib/PACUtils.pm line 3847.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
*** unhandled exception in callback:
***   need an array ref to convert to GArray at /opt/asbru-gtk3/lib/PACUtils.pm line 3847.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
INFO: Finishing (asbru-cm-gtk3) with pid 3847
*** unhandled exception in callback:
***   need an array ref to convert to GArray at /opt/asbru-gtk3/lib/PACUtils.pm line 3847.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
INFO: Received message : [show-conn]-[]
INFO: Finishing (asbru-cm-gtk3) with pid 3847
GLib-GObject-WARNING **: ../glib/gobject/gsignal.c:2647: instance '0x559a2d57bf70' has no handler with id '59019' at /opt/asbru-gtk3/lib/PACMain.pm line 3132.
*** unhandled exception in callback:
***   need an array ref to convert to GArray at /opt/asbru-gtk3/lib/PACUtils.pm line 3847.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
```

**Comment by B1tl0rd** [comment] 2019-11-04 16:26
okay. If I see, I'm not the only one ..
If you detach the window and let it out, it closes, but the connection is open as if it were still flat. and asbru is working, having closed everything.

**Comment by figue** [comment] 2019-11-04 16:29
Maybe related to this commit? https://github.com/asbru-cm/asbru-cm/commit/f5829e2e572f128560bf22b293103d45accbd766

**Comment by gfrenoy** [comment] 2019-11-04 19:11
> On console i see these:
> *** unhandled exception in callback:
> *** need an array ref to convert to GArray at /home/pancio/asbru-cm/lib/PACUtils.pm line 3847.
> *** ignoring at /usr/share/perl5/Gtk3.pm line 572.

Let's try to focus on this first.

This is related to your version of VTE ; can you all let us know which version you are using ?

**Comment by hanspr** [comment] 2019-11-04 20:11
I think is because my commit, that apparently works for versions 52 an below but not above.

![imagen](https://user-images.githubusercontent.com/1572396/68154374-011f5880-ff0d-11e9-8805-e1679c1c0067.png)

Because I do not have a version of vte abobe 52 could not check, I think this would have to be reimplemented like this

![imagen](https://user-images.githubusercontent.com/1572396/68154329-e6e57a80-ff0c-11e9-8db5-164ea24aba98.png)

Could someone be able to check?

**Comment by B1tl0rd** [comment] 2019-11-04 20:28
@hanspr Yes it worked for me!

**Comment by hanspr** [comment] 2019-11-04 20:29
Good, for what I can see I will have to install arch in a VM, to be able to have an environment with the newest vte so I can check for this kind of things.

Sorry

**Comment by gfrenoy** [comment] 2019-11-04 20:33
Thanks @hanspr, I do confirm I was able to reproduce the same issue with Ubuntu Eoan (running VTE 0.58) and that your proposed change does fix it :-)

Just made a commit that should improve this.

@B1tl0rd @figue @panciom Let us know if you can now close tabs with this latest commit.  If you have other problems with the GTK3 branch, don't hesitate to create another issue.

Thanks all for the good collaboration :)

**Comment by figue** [comment] 2019-11-04 21:33
I have tested in a Windows virtual machine (I can't test in "real" Windows Servers for a couple of days) and 611f4c94f0a385f97c0625edcc6d27bd81338ae3 seems to fix the issue. Thank you @hanspr

**Comment by B1tl0rd** [comment] 2019-11-04 21:42
It gives some warning or error when a window / terminal is detached and it is closed, it is possible to say that this warning does not show it when the window works in normal mode.
beyond the warning, to work well.
sorry for bad english
`*** unhandled exception in callback:
***   Can't locate object method "set_icon_pixbuf" via package "Gtk3::Gdk::X11DragContext" at /opt/asbru-gtk3/lib/PACTerminal.pm line 2985.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
sysread() on closed filehandle GEN7 at /opt/asbru-gtk3/lib/PACTerminal.pm line 1569.`

**Comment by hanspr** [comment] 2019-11-04 22:20
This is a different issue and I was looking at it when checking this old issue #70 

If happens when you drag a tab.

If you detach the tab, and you reattach it again, additionally it leaves some other window as a phantom (it will show up if you move the main window)

![imagen](https://user-images.githubusercontent.com/1572396/68162527-cc67cd00-ff1d-11e9-8f95-40b6125ef0f2.png)

This should be moved to issue #70 or open as a new one.

**Comment by B1tl0rd** [comment] 2019-11-04 22:23
OK perfect. Thanks again @hanspr

**Comment by hanspr** [comment] 2019-11-04 22:33
I have checked the gtk manuals and the object and the method are the correct ones.

https://developer.gnome.org/pygtk/stable/class-gdkdragcontext.html

Error

![imagen](https://user-images.githubusercontent.com/1572396/68163639-9b3ccc00-ff20-11e9-9bf8-4ed26530e9f5.png)

Manual

![imagen](https://user-images.githubusercontent.com/1572396/68163648-a1cb4380-ff20-11e9-997e-6474b83e7177.png)

So, it seams to me that the method has been removed in gtk3.

I guess the functionality was to have an image shown while the dragging was executed. So you could see the action.

Commenting the line removes the message. I guess we should find the new methods to recover the animation.

**Comment by hanspr** [comment] 2019-11-04 23:03
Now after writing they are different objects, did not notice at first, similar names but not the same

**Comment by mac-linux-free** [comment] 2019-11-04 23:20
I could not close tabs, too...I´m on Ubuntu 19.10

**Comment by hanspr** [comment] 2019-11-04 23:30
@mac-linux-free 

Pull the last update

    gfrenoy added a commit that referenced this issue 3 hours ago
    @gfrenoy
    Fix call to VTE feed_child for VTE version >= 0.54 (#259) 

If it does not fix, please document procedure to reproduce with images

**Comment by panciom** [comment] 2019-11-05 07:50
Thanks @hanspr. Bug resolved.

**Closed** 2019-11-05 08:40 UTC
Labels: bug, gtk3
