### ISSUE TITLE
edit connection dialog not showed

### ISSUE THREAD

**Issue by khodadadi** [asbru-cm/asbru-cm#572] opened 2020-04-14 17:51 UTC
**Describe the bug**
Edit connection dialog not showed
stdout:
*** unhandled exception in callback:
***   undefined value for mandatory argument 'text' encountered at /opt/asbru/lib/PACEdit.pm line 703.
***  ignoring at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.

**To Reproduce**
1. Go to 'Connections'
2. Click on 'Edit Connection'
3. See error

**Expected behavior**
Open Dialog Box

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 10
 -  Desktop: i3

**Additional context**

**Comment by nikuzz** [comment] 2020-04-14 18:20
I have the same problem on Ubuntu 19.10

**Comment by gfrenoy** [comment] 2020-04-14 18:49
I would assume 6.1.1 but can you confirm the Ásbrú version you are using ?

**Comment by khodadadi** [comment] 2020-04-14 20:07
yes, 6.1.1

**Comment by gfrenoy** [comment] 2020-04-14 20:27
Tried on a live CD of Debian 10.3 Gnome and Ubuntu 19.10 but could not reproduce the issue.

Can you let me know:
- If you have ```proxy ip``` in your connection setting ?
- Does it help if you delete the "cache" file ```.config/pac/pac.nfreeze``` ?
- How/why did you get perl 5.30 installed on Debian 10 ?

**Comment by khodadadi** [comment] 2020-04-14 20:56
proxy? no
delete cache file not fix this issue.
perl 5.30? why not ...?
i use i3 with debian but  asbru detect xfce

`INFO: Ásbrú Connection Manager 6.1.1 (asbru-cm) started with PID 53291
INFO: Desktop environment detected : xfce
INFO: VTE version is 0.60
INFO: Using config directory '/home/user/.config/pac'
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
INFO: Used config file '/home/user/.config/pac/pac.yml'
INFO: Using Gnome tray icon
`

**Comment by nikuzz** [comment] 2020-04-14 21:09
On my workstation the output is
`nico@A7ES-004:~$ asbru-cm
INFO: Ásbrú Connection Manager 6.1.1 (asbru-cm) started with PID 7660
INFO: Desktop environment detected : gnome-shell
INFO: VTE version is 0.58
INFO: Using config directory '/home/nico/.config/pac'
INFO: Used config file '/home/nico/.config/pac/pac.nfreeze'
INFO: Using Gnome tray icon
*** unhandled exception in callback:
***   undefined value for mandatory argument 'text' encountered at /opt/asbru/lib/PACEdit.pm line 703.
***  ignoring at /usr/lib/x86_64-linux-gnu/perl5/5.28/Glib/Object/Introspection.pm line 67.

`

**Comment by khodadadi** [comment] 2020-04-14 21:09
in terminal screen if press alt + e edit dialog opened
i set proxy but not fixed

**Comment by khodadadi** [comment] 2020-04-14 21:13
debian 10 and perl 5:30?  why not?

**Comment by nikuzz** [comment] 2020-04-14 21:14
> hack: in terminal screen if press alt + e edit dialog opened
> i set proxy but not fixed

I can confirm, Alt + E if focus is in connection tree not works, if the focus is in the terminal works.

**Comment by gfrenoy** [comment] 2020-04-14 21:19
> debian 10 and perl 5:30? why not?

I mean: when I start Debian 10.3 ; I get 5.28 so I was wondering how you got this... to be be able to reproduce on the same environment.  If I got it correctly, you're on a Debian Sid, aren't you ?

> I can confirm, Alt + E if focus is in connection tree not works, if the focus is in the terminal works.

Interesting !  I still cannot reproduce this ; sorry :(

Can you try from a "clean" configuration file, you can do this by creating a temporary configuration directory (in ```/tmp/asbru-test``` in this example):

```
asbru-cm --config-dir /tmp/asbru-test
````

Thanks.

**Comment by khodadadi** [comment] 2020-04-14 21:29
rm .config/pac/pac*  will fix this issue

**Comment by gfrenoy** [comment] 2020-04-14 21:32
> rm .config/pac/pac*

Ok but very extreme!  You basically remove everything and you'll need to recreate all your entries !

**Comment by khodadadi** [comment] 2020-04-14 21:34
hah, i exported it  before.

**Comment by gfrenoy** [comment] 2020-04-14 21:41
Ok so I still cannot reproduce with any of my existing connections.

But I suspect some non initialized variable ; I made a commit that should hopefully fix this.

If you revert to your backup ; can you try with the latest 6.1.2 that was just published a few minutes ago ?

**Comment by khodadadi** [comment] 2020-04-14 21:58
perl 5.30 from unstable branch

**Comment by khodadadi** [comment] 2020-04-14 22:00
i switched back to buggy mode. 
when  i remove `pac.yml.tree` issue fixed

**Comment by khodadadi** [comment] 2020-04-14 22:24
@nikuzz 
please backup pac.yml.tree file and remove it , if fixed, compare contents

**Comment by khodadadi** [comment] 2020-04-14 23:57
pac.yml.tree in buggy mode:

<uuid 1>
<uuid 2>
<uuid 3>
tree_page_3:scroll1
tree_page_1:scroll2
tree_page_0:scroll3
tree_page_2:vboxclu

**Comment by khodadadi** [comment] 2020-04-14 23:57
pac.yml.tree content in fixed mode:
<uuid 1>
<uuid 2>
<uuid 3>
tree_page_0:scroll1
tree_page_1:scroll2
tree_page_2:scroll3
tree_page_3:vboxclu

**Comment by khodadadi** [comment] 2020-04-15 00:01
this can help you? @gfrenoy

**Comment by nikuzz** [comment] 2020-04-15 08:53
I upgraded asbru-cm to 6.1.2 and by my side (Ubuntu 19.10 upgraded 2020-04-15) all works correctly now.

**Comment by gfrenoy** [comment] 2020-04-15 09:09
@khodadadi Sorry but I don't see why it would be related to ```pac.yml.tree``` ; can you give it a try with 6.1.2 ; the fix I made would match better what you reported :)

**Comment by hanspr** [comment] 2020-04-15 13:03
@khodadadi 

Could you confirm to me if the lines in PACEdit.pm, of your current install are this (/opt/asbru-cm/lib/PACEdit.pm)

![imagen](https://user-images.githubusercontent.com/1572396/79339875-25855500-7eef-11ea-9e80-70e2142421ac.png)

If so could you edit them to look like this and test if it works with the config files that cause you the error?

![imagen](https://user-images.githubusercontent.com/1572396/79340074-6da47780-7eef-11ea-9c3c-4c690928dc12.png)

**Comment by gfrenoy** [comment] 2020-04-15 13:05
> If so could you edit them to look like this and test if it works with the config files that cause you the error?

That's what has been done in 6.1.2 so testing 6.1.2 is the same :)

**Comment by hanspr** [comment] 2020-04-15 13:08
mmh? I get confused with version that is not master then? is loki? sorry. I do not know where the versions come from.

**Comment by gfrenoy** [comment] 2020-04-15 13:13
> mmh? I get confused with version that is not master then? is loki? sorry.
> I do not know where the versions come from.

master = 6.1.2

6.1.2 was released yesterday
was previously 6.1.1, what was used when this issue has been created

**Comment by nikuzz** [comment] 2020-04-16 11:07
@gfrenoy This morning I had the same problem with the 6.1.2, so not solved. Here the same output:
> nico@A7ES-004:~$ asbru-cm
> INFO: Ásbrú Connection Manager 6.1.2 (asbru-cm) started with PID 16158
> INFO: Desktop environment detected : gnome-shell
> INFO: VTE version is 0.58
> INFO: Using config directory '/home/nico/.config/pac'
> INFO: Used config file '/home/nico/.config/pac/pac.nfreeze'
> INFO: Using Gnome tray icon
> *** unhandled exception in callback:
> ***   undefined value for mandatory argument 'text' encountered at /opt/asbru/lib/PACEdit.pm line 726.
> ***  ignoring at /usr/lib/x86_64-linux-gnu/perl5/5.28/Glib/Object/Introspection.pm line 67.

**I try also with a completely clean config and I finally found why it's happend:**

If I keed the order of the left sidebar tabs like installed ("Connections" is the **first** tabs) all works correctly, If i "drag&drop" the tabs in another order (So that "Connections" is not at the first place), this break the "Edit Connection" function in the connection tree (right click menu option or Atl + E stops works). So what @khodadadi suggested is correct, the order of the tabs (pac.yml.tree) it's the problem. (probably a hard coded "0" position somewhere in searching connection tree in the left side bar)

Here 2 screenshot to better explain what I wrote:
![Captura de pantalla de 2020-04-16 12-55-27](https://user-images.githubusercontent.com/17493820/79449217-20a1cd80-7fe3-11ea-9311-b66d14fcd7c5.png)
![Captura de pantalla de 2020-04-16 12-56-56](https://user-images.githubusercontent.com/17493820/79449227-24355480-7fe3-11ea-8939-70dd271e4b89.png)
![Captura de pantalla de 2020-04-16 12-57-16](https://user-images.githubusercontent.com/17493820/79449239-27304500-7fe3-11ea-90ca-1c8cf2a7db9e.png)

**Comment by gfrenoy** [comment] 2020-04-16 11:23
Waw, didn't even know it was possible to change the order of those tabs!  Thanks everybody for the good troubleshooting session !  I can easily reproduce it now.

Hopefully I can provide a fix soon ; stay tuned.

**Comment by gfrenoy** [comment] 2020-04-16 16:41
The last commit should have fixed the issue.

It was actually a very old bug.  The way David was retrieving the selected node was indeed depending on the position of the tab !  I changed the logic, it should now work as expected.

The change is available in loki and in the latest snapshot that will be released as 6.1.3 soon.

Thanks again for your help on this !

**Comment by KlaasT** [comment] 2020-04-28 09:00
Fixed in 6.1.3. Closed #572

**Closed by KlaasT** 2020-04-28 09:00 UTC
Labels: bug
