### ISSUE TITLE
Terminal transparency not working

### ISSUE THREAD

**Issue by luizlinux** [asbru-cm/asbru-cm#45] opened 2018-01-03 17:24 UTC
Regardless of the tranparency settings in Preferences -> Terminal Options -> Look and Feel, the terminal background is always solid black.

Running asbru-cm-5.0.0-1 on Opensuse.

**Comment by gfrenoy** [comment] 2018-01-03 17:38
Mmm, works fine on my Ubuntu 16.04.

As far as I can see in the code, we rely on Gnome2::VTE to set the transparency.

Questions:
 - Anybody having the same issue on other distributions ?
 - Is there a OpenSUSE live ISO I can download to give it a try on a fresh install ?  All I found so far is an installation media ...

**Comment by luizlinux** [comment] 2018-01-03 17:51
There you go:
https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20180101-Media.iso

Using perl-Gnome2-Vte-0.11-3.6.x86_64 from this repo:
https://build.opensuse.org/project/show/home:stawidy
Reason: perl-Gnome2-Vte from devel:languages:perl requires perl::MODULE_COMPAT_5.181.1 which is not provided by any package on that or other [default] repos.

**Comment by gfrenoy** [comment] 2018-01-03 23:42
Thanks for your help @luizlinux, I was able to start the OpenSUSE VM but my knowledge on this distribution is pathetic so I couldn't find a way to get Ásbrú installed :(

Would mind giving a few instructions to connect to that stawidy repo and get Gnome2::Vte installed ?

And, yes, it will be interesting to see how it behaves on KDE...

**Comment by gfrenoy** [comment] 2018-01-06 16:31
Found this : https://en.opensuse.org/SDB:Add_package_repositories#Zypper

So I did:

    zypper ar -f https://download.opensuse.org/repositories/home:/stawidy/openSUSE_Tumbleweed
    zypper in perl-Gnome2-Vte perl-YAML perl-OSSP-uuid perl-Crypt-CBC perl-Gtk2 perl-Gtk2-Unique perl-Socket6 perl-Net-ARP perl-Crypt-Rijndael perl-Crypt-Blowfish perl-Gtk2-Ex-Simple-List perl-Gnome2-GConf perl-Gtk2-GladeXML perl-Expect perl-IO-Stty

Then something more common:

    git clone https://github.com/asbru-cm/asbru-cm.git
    cd asbru-cm
    ./asbru-cm

And then, yes, indeed, no transparency :(

At this stage, it would be interesting to make a quick test outside Ásbrú and make sure Gnome2::Vte correctly supports transparency on OpenSUSE.

**Comment by gfrenoy** [comment] 2018-01-06 21:22
Played a bit with this the test script (https://github.com/GNOME/perl-Gnome2-Vte/blob/master/t/VteTerminal.t) from [Gnome2::Vte](https://github.com/GNOME/perl-Gnome2-Vte).

If I add ```Gtk2->main;``` at line 99 and run the exact same test on my Ubuntu and the OpenSUSE virtual machine with the [Gnome2::Vte](https://github.com/GNOME/perl-Gnome2-Vte) package from [stawidy](https://build.opensuse.org/project/show/home:stawidy), the outcome is different : on my machine it shows a transparent terminal but not on the OpenSUSE VM...

So there is a problem, for sure but I don't believe it is located in Ásbrú.

Let's keep this issue open for some time (maybe somebody else will have a better solution ?) and after a couple of weeks, if there's no other idea, I'll close the issue as "won't fix".

**Comment by cornfeedhobo** [comment] 2018-01-17 00:57
I can only confirm this issue too, but don't know what could be causing it. I looked at the [spec file](https://build.opensuse.org/package/view_file/devel:languages:perl/perl-Gnome2-Vte/perl-Gnome2-Vte.spec?expand=1) and it doesn't do anything fancy...

**Comment by gfrenoy** [comment] 2018-03-17 16:48
Assuming this bug is caused by an external dependency so it cannot be fixed in this project.

**Closed by gfrenoy** 2018-03-17 16:48 UTC
Labels: help wanted, more information needed
